### ISSUE TITLE
Option to tell esformatter to keep short inlined if-statements

### ISSUE THREAD

**Issue by goloroden** [millermedeiros/esformatter#107]
Usually, I prefer

``` javascript
if (foo) {
  // …
}
```

instead of

``` javascript
if (foo) { /* ... */ }
```

However, I sometimes like to use the second form for verifying parameters and throwing errors / calling callbacks with an error object.

How could one deal with this?

**Comment by amir-s** [comment]
Hello.

It doesn't seem to work with if statements without the opening and closing braces.

```js
if (something) somethingElse();
```

it always gets converted to

```js
if (something)
    somethingElse();
```

Is there anyway config not to touch this?
