### ISSUE TITLE
create a noop preset

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/esformatter#113]
this preset wouldn't make any changes to the input, that way we can implement style changes that are less obtrusive and don't need to reset all the properties (just inherit from the `noop` preset and override the needed options).

this will only be possible after we add support for `-1` to the config options.

PS: issue #1 and #84 are blocking this.

**Comment by bcomnes** [comment]
Would creating a default preset with options to set to `-1` be a good start here?

**Comment by millermedeiros** [comment]
that wouldn't help.. we are planning to kill all the presets besides the default (convert them into plugins). right now even if all settings are `-1` it will still change the code.

**Comment by millermedeiros** [comment]
I'm not going to work on this.. if you don't want the code to change use a different tool, maybe `echo` or `tee` :stuck_out_tongue_winking_eye:

**Comment by bcomnes** [comment]
Thats fair given the work involved :)

**Comment by millermedeiros** [comment]
**for future reference:**

we have a bunch of calls to [`limit` that passes a number as second argument](https://github.com/millermedeiros/esformatter/search?utf8=%E2%9C%93&q=limit&type=Code) - these changes will always happen, no matter what settings you pass. Most of the cases are actually things that you want to happen (eg. always enforce a single space after the `new` keyword), but in some cases they are hardcoded just because we didn't have a name for that option or didn't think anyone would need to configure that...

There is also the `indent.sanitize` call (which will remove the original indentation) - we always re-indent the whole file, but this should be easy to ignore with a flag...
