### ISSUE TITLE
Option for newline for Array declarations

### ISSUE THREAD

**Issue by shellscape** [millermedeiros/esformatter#129]
I'd love to see an option for newlines for Array blocks. There are whitespace options but no newline options. 

Before:
```javascript
[ 'one', 'two', 'three' ]
```

After:
```javascript
[
  'one',
  'two',
  'three'
]
```

**Comment by millermedeiros** [comment]
reopening since we decided to not close `plugins-wishlist` bugs until they are implemented

**Comment by jzaefferer** [comment]
There's now a plugin to collapse arrays based on length: https://github.com/wbinnssmith/esformatter-collapse-objects (also added to wiki)
