### ISSUE TITLE
should presets be plugins?

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/esformatter#189]
I just processed jQuery 2.1.1 on esformatter@0.4.0 with the jquery preset and there are some changes that we do to the code that are different from what a developer would do (edge cases based on the context), but I think they are unique to jquery style guide and really can't be represented easily with just integers/strings/booleans (and would be very easy to implement as a plugin)..

I also think that maintaining a large set of presets inside esformatter codebase will be PITA to maintain.. more test files and each change to the style guide will need a version bump on esformatter itself.

plugins can override the settings on the `setOptions` hook (if they are just presets) and can be released separately from esformatter and npm is a great way to install dependencies.

/cc @jzaefferer

**Comment by bcomnes** [comment]
I think this would be a good idea, as it would promote the use of plugins to provide a preset.  https://github.com/maxogden/standard-format would make a good preset, but it would be better if it could be kept in its own repo by people who are interested in maintaining it.

**Comment by millermedeiros** [comment]
presets should really become plugins, closing this in favor of #249
