### ISSUE TITLE
[META] support ES6 features!

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/esformatter#192]
as long as it is supported by esprima it should be fairly easy to add it. (eg. `ArrowFunctionExpression`)

**Comment by lukescott** [comment]
Esprima 2.0 was released 20 days ago, which has (partial) ES6 support. 6 days ago class support was added to the master branch.

**Comment by millermedeiros** [comment]
@lukescott just tested `esprima@2.0` and it only introduced a single regression to the esformatter tests.. and it is definitely an edge case (probably related to `EmptyStatement` not existing anymore on the AST)

**Comment by millermedeiros** [comment]
I just published `rocambole@0.5` which uses `esprima@2.0`, so now we can start adding tests and support for ES6 features \o/

**Comment by ruyadorno** [comment]
:tada: :tada: :tada:

**Comment by eduardolundgren** [comment]
Thank you @millermedeiros :)

**Comment by RaitoBezarius** [comment]
What about replacing esprima by babel (which supports more ES6 features _afaik_) ?
Is that possible? I can help, if it is not too complicated.

**Comment by bobbyrenwick** [comment]
:+1:

**Comment by millermedeiros** [comment]
@RaitoBezarius babel uses acorn internally and we would have the same issues with the token ranges (would require changes to the way we detect the start/end of nodes). right now we are *trapped* with esprima v2.

it would be helpful if we had new bugs for each ES6 feature that we don't format properly yet, with **input** and **expected outuput**. I don't even know which features are supported by esprima at the moment...

**Comment by millermedeiros** [comment]
I believe we covered all the ES6 features on v0.7; if anything else is missing/wrong please open as a separate bugs. Thanks.

**Comment by eduardolundgren** [comment]
Thank you @millermedeiros :)

**Comment by kewah** [comment]
good work :+1:

**Comment by tommmyy** [comment]
Is there possibility that esformatter does not support static class properties (it is included by Babel in stage 0)?

**Comment by millermedeiros** [comment]
@tommmyy for now we can only support features that are implemented by [espree](https://github.com/eslint/espree). which doesn't support experimental features so far.
