### ISSUE TITLE
Comment alignment

### ISSUE THREAD

**Issue by nzakas** [millermedeiros/esformatter#209]
I'm not sure if there's a way to do this already, but I'd like some comments to stay with the previous line's indentation. For example:

```
switch(foo) {
    case bar:
        baz();
        // falls through

    case biz:
        what();
}
```

Right now, ESFormatter converts it to:

```
switch(foo) {
    case bar:
        baz();
    // falls through

    case biz:
        what();
}
```

I think this could be generalized to say a comment that is not preceded with an empty line and is followed by an empty line should be indented to the previous code line's indent. (Maybe this could just be a new option to turn off or on?)

**Comment by millermedeiros** [comment]
the pull request #282 updates the comment indentation behavior to match this but I'm just not sure if all the changes makes sense (ie. comments inside empty blocks..) - feedback is highly appreciated, should land the PR in the next few days (maybe next week)

**Comment by jzaefferer** [comment]
I just tested #282 by running it against jQuery UI. I haven't noticed any regressions, and #270 is fixed. Looks good to me.
