### ISSUE TITLE
Object literals on one line

### ISSUE THREAD

**Issue by nzakas** [millermedeiros/esformatter#210]
Most of my projects say that an object literal with a single property should be on one line (such as `{ foo: 'bar'}`) but if there's more than one property, it should be on multiple lines. Right now, ESFormatter formats all object literals the same way, so even those with one property end up spread across three lines. I'd like to be able to keep object literals with one property to be on one line.

Is there a way to configure this behavior?

**Comment by millermedeiros** [comment]
reopening since we decided to not close `plugins-wishlist` bugs until they are implemented

**Comment by millermedeiros** [comment]
closing since it was implemented as a plugin! https://github.com/wbinnssmith/esformatter-collapse-objects
