### ISSUE TITLE
Add support for variable renaming

### ISSUE THREAD

**Issue by pomeh** [millermedeiros/esformatter#214]
If you really want to "be the best JavaScript code formatter" (and I want you to become it because I need this tool !!), `esformatter` should definitely support renaming variable in some form. To understand what I mean you have to check out this online but closed-source JavaScript formatter: http://www.jsnice.org.
There are two things involved in this tool:
- renaming local variable (based on some sort of neural network  I guess, or any kind of memory, artificial intelligence or whatever)
- interactive variable renaming, which allow you to rename a variable in the formatted code

I don't know if esformatter could support this second point in any form but if yes it would be really, really powerful :)

**Comment by millermedeiros** [comment]
another plugin: https://github.com/twolfson/esformatter-phonetic
