### ISSUE TITLE
Plugin development: incorrect indention

### ISSUE THREAD

**Issue by evanvosberg** [millermedeiros/esformatter#216]
I'm currently working on the [esformatter-onevar](https://github.com/evanvosberg/esformatter-onevar) plugin (it's still under development).

My plugin uses the `transformBefore` hook and I would expect all formatting will be done afterwards. But on the first run the indention is not correct.

Why does this happend?   

Source:
```js
var foo = true,
    bar;

function a()  {
    var foo = 'foo',
        bar = 'bar';
}

var more = false;

function b()  {
    if (a) {
        var bar = true;
    }

    var foo = 'foo',
        bar = 10;
}

for (var i = 0, l = bar.length; i>l; i++) {
    foo += ' ' + i;
}

if (foo)
    var claus = true;
```

After first run `esformatter.format()`:
```js
var foo = true,
    bar,
    more,
    i,
    l,
    claus;

function a() {
    var foo = 'foo',
        bar = 'bar';
}

more = false;

function b() {
    var bar,
    foo;
    if (a) {
        bar = true;
    }

    foo = 'foo';
    bar = 10;
}

for (i = 0, l = bar.length; i > l; i++) {
    foo += ' ' + i;
}

if (foo) {
    claus = true;}
```

After second run `esformatter.format()`:
```js
var foo = true,
    bar,
    more,
    i,
    l,
    claus;

function a() {
    var foo = 'foo',
        bar = 'bar';
}

more = false;

function b() {
    var bar,
        foo;
    if (a) {
        bar = true;
    }

    foo = 'foo';
    bar = 10;
}

for (i = 0, l = bar.length; i > l; i++) {
    foo += ' ' + i;
}

if (foo) {
    claus = true;
}
```

**Comment by millermedeiros** [comment]
yes, it is definitely rocambole fault. basically when you add nodes or change the position they don't have the proper `depth` attribute so they are probably being skipped during the transformation.. I'm going to change the way it works so that we force a new `instrumentNodes` before doing the moonwalk.

one thing tho is that we might actually need to instrument the nodes after each plugin transform call because they might have changed the AST structure.. to be honest I'm almost killing the `transformBefore` and `transformAfter` and just recommending the use of `stringBefore` and `stringAfter`.

**Comment by millermedeiros** [comment]
definitely thinking about deprecating `transformBefore` and `transformAfter`, it will be easier and in the long run it will be the best for the ecosystem (will motivate plugin authors to write tools that can be used outside of esformatter).

**Comment by millermedeiros** [comment]
going to close this as wontfix since our solution will be actually to deprecate the `transformBefore`

**Comment by millermedeiros** [comment]
reopening this.. there seems to be an easy fix on `rocambole.moonwalk`.. sorry for all the back and forward.

**Comment by millermedeiros** [comment]
ahh.. forget it.. we can't really ensure that all nodes have `startToken` and `endToken`. so my *easy fix* won't really work.. will really ask plugin authors to not use `transformBefore` and `transformAfter` to edit the AST structure. it should only be used to manipulate WhiteSpace, LineBreak and Indent tokens.

**Comment by evanvosberg** [comment]
This would be bad, because in the past I also used esformatter to modify the syntax like ensure only one var in a function scope, see [esformatter-onevar](https://github.com/brix/esformatter-onevar)

**Comment by millermedeiros** [comment]
@evanvosberg you can fix it by changing the `transformBefore` method into a `stringBefore` and call `rocambole.parse(str)` by yourself (and keeping the same logic as you currently have).

I'm planning to add support for the [pipe config](https://github.com/millermedeiros/esformatter/issues/168) so plugins that only needs `stringBefore` or `stringAfter` should probably be implemented as standalone executables moving forward (that way you can use it outside of esformatter as well).
