### ISSUE TITLE
Formatting "`if` statement with `delete` and comma" is not idempotent

### ISSUE THREAD

**Issue by twolfson** [millermedeiros/esformatter#222]
I have been exploring using `esformatter` with minified JS and ran into an issue with reformatting already formatted content. I noticed that `esformatter` does not maintain the same indentation but uses a new one. The following code toggles between 2 indentations when `esformatter` formats it:

Gist: https://gist.github.com/twolfson/e3433283b0f37ef36854

```js
var obj;
if (
  delete obj.hello
  , 'world') {
  // more code
}
```

```js
var obj;
if (
delete obj.hello
  , 'world') {
  // more code
}
```

**Comment by millermedeiros** [comment]
now it should work as expected! sorry for the huge delay. will release a new version soon including this fix.

**Comment by twolfson** [comment]
Glad to see it patched eventually :tada:

**Comment by twolfson** [comment]
I have run the latest `esformatter` against the minified script. Everything is consistent except for 1 line between the first and second run. Everything is consistent after the second and third rerun which is great. I will open an issue for the bug. Thanks again for the fix!
