### ISSUE TITLE
Default keyboard mapping collides with "replace"

### ISSUE THREAD

**Issue by tschneidereit** [millermedeiros/esformatter#235]
`cmd+alt+f` is the mapping for `replace` on mac. While I really like my source code to be formatted, being able to search & replace with a shortcut is slightly more important :)

I have changed the binding to `cmd+alt+l` - AFAICT that's not used for anything else.

**Comment by jzaefferer** [comment]
Are you referring to https://github.com/piuccio/sublime-esformatter ? You should report it there.

**Comment by tschneidereit** [comment]
Ugh, I copied the first github link from their README, without ensuring that it's for the project that I *really* meant. I'm sorry and embarrassed :/
