### ISSUE TITLE
Bad indent of multi-line call expression arguments

### ISSUE THREAD

**Issue by jzaefferer** [millermedeiros/esformatter#238]
All of these combinations are improperly indented:

```js
// CallExpression with one ArrayExpression an one ObjectExpression arguments
x([
  a
], {
  b: 0
});


// CallExpression with two ObjectExpression arguments
x({
  a: 1
}, {
  b: 0
});

// CallExpression with one ArrayExpression and one FunctionExpression arguments
// works fine when ArrayExpression is on one line
x([
  bar
], function() {
  y();
});

// CallExpression with one ObjectExpression and one ArrayExpression arguments
x({
  a: 1
}, [
  b
]);
```
Result:

```js
// CallExpression with one ArrayExpression an one ObjectExpression arguments
x([
  a
], {
    b: 0
  });


// CallExpression with two ObjectExpression arguments
x({
  a: 1
}, {
    b: 0
  });

// CallExpression with one ArrayExpression and one FunctionExpression arguments
// works fine when ArrayExpression is on one line
x([
  bar
], function() {
    y();
  });

// CallExpression with one ObjectExpression and one ArrayExpression arguments
x({
  a: 1
}, [
    b
  ]);
```

These were previously reported as #227 and #217. I've taken the tests reported there and simplified them. #201 might be related as well, but since it doesn't involve a call expression, I can't yet tell.

Might have been cause by 4736c146e32aaf7103700c0141db2e02a6ff7f07.

**Comment by jzaefferer** [comment]
@millermedeiros I've debugged this one multiple times, but still haven't gotten anywhere. I suspect the issue to be in either `lib/hooks/CallExpression.js` or in `lib/indent.js`. Since the latter remains cryptic to me, I can't really tell.

This is one of the few remaining blockers for me. I hope you can look into this some time soon.

**Comment by millermedeiros** [comment]
I think this can be fixed by changing the way the `CallExpression.getIndentEdges` work to only indent the arguments if the first argument starts on a different line, eg:

```js
// don't indent
foo({ a: b });
foo({
  a: b
});

// indent
foo(
  {a : b}
);
foo(
  {
    a: b
  }
);
```

so basically return `false` if there is no line break between `openingParentheses` and the `node.arguments[0].startToken`.

**Comment by millermedeiros** [comment]
I don't really know why I added the [`indent3` test to CallExpression](https://github.com/millermedeiros/esformatter/blob/master/test/compare/default/call_expression-in.js#L81-L84) this behavior is really weird and I couldn't map it to any issue.. I think we should change the way the code behaves on this case.

I'm going to provide a patch in the next 30min that fixes this problem.

**Comment by millermedeiros** [comment]
`indent3` test does actually make sense.. the implementation that is wrong. we can keep both behaviors.
