### ISSUE TITLE
Lack of indent on multi-line arrays and strings

### ISSUE THREAD

**Issue by jzaefferer** [millermedeiros/esformatter#239]
Both of these get wrong indent:

```js
var data = [1,
  2];

var x = "abc" +
  "efg";
```

Result:
```js
var data = [1,
2];

var x = "abc" +
"efg";
```

Neither the hook for ArrayExpression nor for BinaryExpression are particularly complicate, but similar to #238, I don't understand enough to figure out the problem. 

This is one of the few remaining blockers for me.

**Comment by jzaefferer** [comment]
The multi-line string / binary expression portion is a duplicate of #212.

**Comment by millermedeiros** [comment]
for the array we basically need to replicate the logic that I just added to the CallExpression (indent if array item starts on the next line) - I probably won't have time to work on it this week, but should not be too complex to implement.

PS: the current `ArrayExpression.getIndentEdges` logic seems weird to me so it is probably a better idea to replace the whole thing than try to adapt it.

**Comment by jzaefferer** [comment]
I still have no mental concept of what `getIndentEdges` is doing. Some explanation, e.g. in `contributing.md`, might help a lot for that.

**Comment by millermedeiros** [comment]
@jzaefferer I pushed a commit a few hours ago explaining how indentation works, let me know if you need more info about: https://github.com/millermedeiros/esformatter/commit/3ff435502276f0c152a17fae5e9d44ad40c1c396 - this was indeed a very good idea, will make it way easier for new contributors to jump into the project

**Comment by jzaefferer** [comment]
I just looked at the commit - that's still mostly incomprehensible to me...
