### ISSUE TITLE
Bad indent after multi-line argument inside call expression

### ISSUE THREAD

**Issue by jzaefferer** [millermedeiros/esformatter#240]
In this case, the secon argument (`expected`) is over-indented:
```js
equal(
  y
    .find()
    .length,
  expected
);
```
Result:
```js
equal(
  y
    .find()
    .length,
    expected
);
```

Another indent issue, same disclaimer as for #238 and #239: Blocker, I can't figure it out.

**Comment by millermedeiros** [comment]
this is probably an edge case related to the chained expression edges (`ObjectExpression.getIndentEdges`) I did not try to identify the root cause yet but I would start with a basic `console.log` on the `getIndentEdges` and see if it is getting the wrong `endToken`.
