### ISSUE TITLE
.setOptions in plugin not taking effect

### ISSUE THREAD

**Issue by bcomnes** [millermedeiros/esformatter#243]
I'm probably doing something wrong here, so please bear with me:

If I take a working config file that works great when specified with `esformatter -c` eg: https://github.com/maxogden/standard-format/blob/master/rc/esformatter.json

and Wrap it up as a plugin:
https://github.com/bcomnes/esformatter-standard/blob/master/index.js

The settings don't actually take effect when loaded as a plugin they way they do when loaded as a configuration file.  

Any ideas?

**Comment by millermedeiros** [comment]
you need to override the `opts` object properties, on your example you just changed the value of the local variable `opts`.

you basically need a [`deepMixIn` function](http://moutjs.com/docs/latest/object.html#deepMixIn) to copy all the properties from your `standardPreset` into the `opts` object.

**Comment by millermedeiros** [comment]
if that doesn't solve your problem please reopen the bug.

**Comment by bcomnes** [comment]
Cool Thanks for the pointer!  I'll try it out.

**Comment by bcomnes** [comment]
@millermedeiros That seemed to do the trick.
