### ISSUE TITLE
create a new project that handles the test logic automatically for plugin authors

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/esformatter#247]
we should make it as easy as possible for plugin writers to test their code. so it would be great if we could abstract our test infrastructure into a dedicated module that can be reused by all/most plugins.

**Comment by jzaefferer** [comment]
Would that include the existing tests? Those might be useful to verify a plugin doesn't cause regressions.

**Comment by royriojas** [comment]
I used a very generic approach for the tests of this plugin :)

[esformatter-jsx-ignore](https://github.com/royriojas/esformatter-jsx-ignore)

It was shameless taken from [esformatter-braces](https://www.npmjs.com/package/esformatter-braces)

But it actually works well, just provide the desired input as file and compare against the desired one as text also. Works well I guess and is pretty generic. We should also test that the plugin load the configuration and other stuff, but I found this way very easy to handle several assertions in a generic way

**Comment by millermedeiros** [comment]
the main problem of mocha and other test runners is that the string diff is usually not really clear for JavaScript programs, the custom mocha version we use on esformatter is way easier to see the errors (since we do a diff based on chars and use colors to highlight the differences)

I implemented something very simple on [esformatter-semicolon-first](https://github.com/millermedeiros/esformatter-semicolon-first/) using [diff](https://www.npmjs.com/package/diff) and esformatter as the only dependencies for the tests, but I know that it won't fit all the needs..

we can't really share our tests with the plugins because they might be changing the default behavior which would break our tests anyway...

plugins might want to compare the input/output in many different ways (external files, local strings) so it's hard to abstract it in a way that would work for everyone. on esformatter since we have so many tests I end up using `BAIL=true npm test` and `GREP=array npm test` very often, I also like the fact that we have multiple files.

I guess we will need to ignore this feature request and let plugin authors copy each other and figure out the best way to do it.

**Comment by millermedeiros** [comment]
marking as invalid since it's too hard to do it properly, every project/developer have different needs.

**Comment by jzaefferer** [comment]
I just looked at https://github.com/millermedeiros/mocha - maybe you can update the readme a bit to document how to use this like esformatter does?
