### ISSUE TITLE
Spacing around call expression when IIFE

### ISSUE THREAD

**Issue by jzaefferer** [millermedeiros/esformatter#250]
While testing the latest bug fixes (looks great!), I ran into this issue:

```js
( function( $ ) {
x;
}( jQuery ) );
```

Its currently formatted like this:

```js
(function( $ ) {
x;
}( jQuery ));
```

Setting `whiteSpace.[before|after\.CallExpression` to 1 will "fix" this, but of course it breaks every other call expression. I don't know how to configure this, or if there is no way to configure it, how to address it elsewhere.

**Comment by millermedeiros** [comment]
we should add another setting or create a plugin that handles this case.. I couldn't think of a good name for it, specially since IIFE might not be surrounded by parenthesis:

```js
;!function(x){
console.log(x)
}('bar')
```

issue #223 is related to this
