### ISSUE TITLE
Promise indentation

### ISSUE THREAD

**Issue by jish** [millermedeiros/esformatter#252]
Apologies if this is a duplicate, I looked around the issues list, the test suite, and the configuration options and did not find anything referring to promise indentation.

I have a code block that looks like the following:

```js
promise().then(function(foo) {
  return x;
}, function(bar) {
    return y;
  });
```

I would expect it to be formatted as follows:

```js
promise().then(function(foo) {
  return x;
}, function(bar) {
  return y;
});
```

Are there any options I can set to get the desired behavior?

**Comment by millermedeiros** [comment]
this is a known bug and already fixed on master. it was a bug in the way we handled arguments indentation.

see: #238

**Comment by jish** [comment]
Cool, thanks! :)

**Comment by millermedeiros** [comment]
v0.5.0 (released today) contains this fix. try it out and let me know if you find any bugs. reduced test cases (like the one you provided on this bug report) are extremely helpful.
