### ISSUE TITLE
Minified `if` statement with `return` statement inconsistent indentation between first and second formatting

### ISSUE THREAD

**Issue by twolfson** [millermedeiros/esformatter#256]
As in #222, I have been using `esformatter` with minified JS. This is not a major problem as after the second reformatting, the output stays consistent. However, between the first and second formatting, there is a shift between formats. I have created a gist to reproduce easily:

Gist: https://gist.github.com/twolfson/53c34abb360029493ac3

```js
function main() {
  do
    if (true) return 1;
  while (true);
}
```

```js
function main() {
  do
  if (true) return 1;
  while (true);
}
```

**Comment by millermedeiros** [comment]
it was a real bug on the `DoWhileIndentation`, it was using the `body` as the first indent edge.. in this case the `body.startToken` was the `if` keyword, the indent works by looking for line breaks in between the `startToken` and `endToken` so it ignored the indentation on this line.. maybe I should just change this assumption on the indent logic and search if `startToken` is preceded only by white spaces and line breaks (unsure on how much that would break the current hooks)

**Comment by twolfson** [comment]
Geez, that's confusing. I think `startToken` is probably the best way to go about it. I usually don't consider end token when handling whitespace unless the token itself is a closing brace.

The easiest approach would be to always inject whitespace everywhere but then you lose out on maintaining cases where we want minimal whitespace.

**Comment by millermedeiros** [comment]
yeah.. just tested and it's indeed a bad idea to check automatically if there is a line break before `startToken` during indentation. breaks a few of the existing tests and there is a higher chance of introducing mistakes (too much magic, not intuitive). so far our best chance is to just add more test cases and handle each edge case "manually" (like I did on this bug).

**Comment by millermedeiros** [comment]
@twolfson I tried the approach of removing all the whitespace between tokens before inserting new ones.. also tried to always indent on line breaks and count matching `)` and `}`, even tho they are simpler to implement, they don't give as much flexibility and there are cases that are *impossible* to implement.. so I took the harder path and decided to support the `-1` settings, even tho esformatter still changes a few things even if the config file sets all the options to `-1` (there are some things that aren't configurable)

keep the bug reports coming!
