### ISSUE TITLE
Plugin author: How to keep comment indent in sync?

### ISSUE THREAD

**Issue by jzaefferer** [millermedeiros/esformatter#259]
I have a plugin that changes indent on MemberExpression properties, which works fine in principle. It breaks down once I sprinkle a few line comments on it. Those need to be updated as well, when the following line of code changes.

I've looked through this project to see if there's some way to reuse the indent logic for line comments, but came up empty. I thought about looking for previous LineComment tokens and updating their indent just like I do it with the MemberExpression properties, but I don't know how to restrict that search properly, since there could be 0, 1 or multiple previous line comments.

**Comment by millermedeiros** [comment]
do you have an example input and output just so I can understand exactly what you are trying to achieve?

**Comment by millermedeiros** [comment]
the easiest way to limit the search is probably to use the `_tk.findPrevNonEmpty(searchStart)` and check if `_tk.isComment(prevNonEmpty)`.. keep doing it until you reach something that isn't a comment and update the indent in between the first comment and your `searchStart`.

**Comment by millermedeiros** [comment]
it would be good if we had a standalone module that exposed methods to add/remove/update indent in between 2 tokens.

**Comment by jzaefferer** [comment]
Here's a sample of the desired output:

```js
element
    .parent()
		.height( 300 )
	.end()
	.accordion();
    
// comment
element
    // comment
	.parent()
		// comment
		.height( 300 )
	// comment
	.end()
	// comment
	.accordion();
```

**Comment by jzaefferer** [comment]
I made a bit of progress, but haven't figured it out quite yet. The plugin now lives in a git repo: https://github.com/jzaefferer/esformatter-jquery-chain - running `npm install && npm test` should try to format `expected.js`, dump the result on the console and fail the assert. Its not all bad, but for example I end up with this over indented comment:

```js
element
	.children()
		.bla()
		.blu()
		.parent()
					// comment
			.height( 300 )
		.end()
		.accordion();
```

The relevant logic is in `updateLineComments`:

```js
function updateLineComments(node, nested) {
  var search = node.property.startToken;
  while (search && search !== node.startToken) {
    search = _tk.findPrevNonEmpty(search);
    if (_tk.isComment(search)) {
      addIndent(search, nested);
      return;
    }
  }
}
```
Would appreciate some help figuring that out. Its pretty close...

**Comment by millermedeiros** [comment]
Did not check the code yet but I believe the easiest solution would be to
"replicate" the same indent as the next line.

**Comment by jzaefferer** [comment]
I've created an issue for this in my plugin's repo: https://github.com/jzaefferer/esformatter-jquery-chain/issues/1
