### ISSUE TITLE
Try / Catch statements are not indented properly

### ISSUE THREAD

**Issue by royriojas** [millermedeiros/esformatter#264]
This will transform this:

```javascript
  try {
   something();
  } catch (ex) {
    err && err( ex ); // this will have 2 extra spaces
  } finally {
    finallyFn && finallyFn();
  }
};
```

in to this

```javascript
  try {
   something();
  } catch (ex) {
       err && err( ex ); // this will have 2 extra spaces
  } finally {
    finallyFn && finallyFn();
  }
};
```

I have tracked down the issue to rocambole. Since it only affected new installations it was clear it was an issue with the dependencies so since rocambole uses esprima@^2.0, sometimes it gets esprima@2.1.0 which seems to make the beautifier to add 2 extra spaces to the catch statements.

I chose to use `npm shrimwrap` to close the problem I have on [esbeautifier](https://www.npmjs.com/package/esbeautifier) which is a wrapper around your tool to actually overwrite the content of the files. But it would be nice to have the dependency locked in rocambole.

That way I can get rid of the `shrimwrap` trick.

**Comment by millermedeiros** [comment]
I'll test against esprima@2.1.0, they probably changed the `range` of some node.. there is probably a way to make it work with both versions of esprima but we should always try to target the latest version because of newer features (ES6).

**Comment by royriojas** [comment]
You're right,

let me know if you need help reproducing the issue.

**Comment by millermedeiros** [comment]
this was caused by https://github.com/jquery/esprima/issues/1031 - we would loop over each `CatchClause` twice, adding 2 indents instead of one.
