### ISSUE TITLE
Can CallExpression parentheses be formatted?

### ISSUE THREAD

**Issue by briandipalma** [millermedeiros/esformatter#267]
Hi,

Given this code,

```javascript
var oXmlResourceService = require ('service!br.xml-service'); 
```

I'd like to format it to not have the space before the `('service!...` is that possible?

**Comment by millermedeiros** [comment]
this was supposed to not have a space by default, so it's a bug on the `lib/hooks/CallExpression.js`

**Comment by millermedeiros** [comment]
in fact we do need an option:

```js
// input
var Sidebar = Backbone.Model.extend({
   //... 
});

// output
var Sidebar = Backbone.Model.extend
({
   //... 
});
```

yes, this is a weird style but was asked here:  https://twitter.com/andersonaguiar/status/576414404285231104

**Comment by andersonaguiar** [comment]
It was only an example, I don't use this way.

I implement in Javascript something of PSRs from PHP, this is a good example for have a base http://www.php-fig.org/psr/psr-2/.

**Comment by andersonaguiar** [comment]
That issue already was merged in the live preview?
