### ISSUE TITLE
Indent issue with comment in front of CatchClause

### ISSUE THREAD

**Issue by jzaefferer** [millermedeiros/esformatter#270]
Expected:
```js
try {
  bla();
// comment
} catch(e) {
  throw e;
}
```
Actual:
```js
try {
  bla();
  // comment
} catch (e) {
  throw e;
}
```

**Comment by millermedeiros** [comment]
uhm.. I don't consider this as a bug because the comment is inside the `{}` and the current indent logic is to add a new indent level to each line in between the `startToken` and `endToken`.

do you think we should change the indent behavior to always make comments match the indentation of the next line? it should not be that complex to implement it we do the indentation *backwards* (start from `endToken`)

**Comment by jzaefferer** [comment]
We already have that by default in other contexts, [for example](https://github.com/millermedeiros/esformatter/blob/abd9365d99c28056e9b08d99caca785fc87c0247/test/compare/default/if_statement-out.js#L139) before `} else`.

> do you think we should change the indent behavior to always make comments match the indentation of the next line? it should not be that complex to implement it we do the indentation backwards (start from endToken)

That sounds good to me.

**Comment by jzaefferer** [comment]
I've looked at `lib/indent.js`, but I'm still rather clueless how to approach the implementation. It sounds like we'd need to iterate over all tokens from end to start, and for every `LineComment` token, adjust the indent to match that of the following line. Does that sound right? If so, where would that have to happen? Is there a method in rocambole for that, or do we only need a simple loop that goes through `token.prev`?

**Comment by millermedeiros** [comment]
we don't have a method for that so far but I would like to see a new lib (maybe `rocambole-indent`?) that contains the methods needed to add/remove indent in the future, so plugins could reuse it... I was going to do that over the weekend but got sidetracked.

PS: it's OK to keep everything inside esformatter for now, but I have the plan to extract as many helpers as possible moving forward.

**Comment by millermedeiros** [comment]
this is kinda similar to #209 - maybe we should handle both cases at once.

**Comment by jzaefferer** [comment]
That seems reasonable. For both `[blank line][line comment][code]` and `[code][line comment][blank line]`, use the indent of the `[code]` for the `[line comment]`. Then figure out the other variations from there.
