### ISSUE TITLE
issue with executing esformatter from CLI

### ISSUE THREAD

**Issue by DaveDH2** [millermedeiros/esformatter#271]
± |master ?:1 ✗| → esformatter index.js
Can't parse configuration file: "/Users/DaveDH2/.esformatter"
Exception: Unexpected token

created a ~/.esformatter and installed the packages.
https://gist.github.com/DaveDH2/548306f1878dd85c0f26

**Comment by kewah** [comment]
There is an extra comma line 7 https://gist.github.com/DaveDH2/548306f1878dd85c0f26#file-esformatter-L7 You need to remove it otherwise the json is not valid

**Comment by DaveDH2** [comment]
Ah, thanks... I did remove it, and I still encounter the same error.

**Comment by millermedeiros** [comment]
weird.. it was supposed to diplay the `Unespected token` like:

```
Can't parse configuration file: "/Users/millermedeiros/.esformatter"
Exception: Unexpected token \

Can't parse configuration file: "/Users/millermedeiros/.esformatter"
Exception: Unexpected token }
```

if you can't see the invalid token, it's probably some [weird unicode space](https://www.cs.tut.fi/~jkorpela/chars/spaces.html) - try running your config into a [JSON validator](http://jsonlint.com/) and/or [JSON formatter](http://jsonformatter.curiousconcept.com/).

this error message is generated by a simple [`JSON.parse()`](https://github.com/millermedeiros/esformatter/blob/d87b282c47da792f7213a6226086d6137981fa6e/lib/options.js#L143-L148) call.

**Comment by DaveDH2** [comment]
I ran it against JSON formatter, it it was valid. 

It turns out, because some setting in my .vimrc that my paste is doing something different.. anyways I open/pasted in sublime, it works like a charm now.

Thank you, both of you, for helping me out.
