### ISSUE TITLE
extract helper methods from lib/indent.js into its own module

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/esformatter#277]
it will be extremely useful for plugins to be able to increase/decrease the indent level in between tokens, so I think we should maintain these methods as a separate module to encourage code reuse.

we should not extract the whole file, only extract pure functions that are useful in different contexts (similar to what we did with [rocambole-token](https://github.com/millermedeiros/rocambole-token)) - we tried to maintain the indentation as a separate project before and it was a PITA to keep both projects in sync and to test everything.

see #270

**Comment by jzaefferer** [comment]
Extracting functions for adding and removing indent sounds good, I could use that in my esformatter-jquery-chain plugin.

**Comment by millermedeiros** [comment]
wow.. this was harder than expected.. spent the past 3h working on this: https://github.com/millermedeiros/rocambole-indent - I still plan to add the logic to align the comments before publishing v1.0.0 (maybe do it inside the `sanitize` method)

I ended up changing a lot in the esformatter indentation logic but I think it was for the better.. now we support negative indent levels!! - will create a pull request soon with my work in progress branch.
