### ISSUE TITLE
extract lib/whiteSpace.js into its own module

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/esformatter#278]
these methods are pretty solid (long time since we changed anything) and are extremely useful for plugin authors. - we should definitely extract them.

maybe name it `rocambole-ws` or `rocambole-whitespace` so it's similar to [`rocambole-token`](https://github.com/millermedeiros/rocambole-token)

**Comment by jzaefferer** [comment]
:+1: to `rocambole-whitespace`

**Comment by millermedeiros** [comment]
pushed rocambole-whitespace v1.0.0 to npm! https://www.npmjs.com/package/rocambole-whitespace
