### ISSUE TITLE
CLI never returns with `-i` param

### ISSUE THREAD

**Issue by franleplant** [millermedeiros/esformatter#281]
Hi!
    Im running esformatter in the CLI as follows:

```sh
esformatter -c ~/opts.json -i file.js
```

And it never returns from that, like it never finishes the Job.
Im using Ubuntu 14.04 and node 0.10.35.

Please tell me if I can help you with any more data about the incident.

**Comment by millermedeiros** [comment]
@franleplant might be because you are using v0.5.0 and this feature will only be available on v0.6.0 so it's considering the `file.js` is actually the value of `-i` and expecting it to read the input file from `stdin`

**Comment by millermedeiros** [comment]
try `esformatter -v`  and also check if `esformatter --help` lists the `-i` option

**Comment by millermedeiros** [comment]
marking as invalid and closing it for now since v0.6 was not released yet.

**Comment by franleplant** [comment]
Yes, you are right, thanks for your help!

Is there any release date for v0.6.0 ?

**Comment by millermedeiros** [comment]
I plan to release until April 13, but might happen before that since we only have a few bugs [flagged for v0.6 open](https://github.com/millermedeiros/esformatter/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.6.0) at the moment
