### ISSUE TITLE
Bad indent for closing brace of IfStatement inside SwitchStatement

### ISSUE THREAD

**Issue by jzaefferer** [millermedeiros/esformatter#290]
Input/expected:

```js
switch (x) {
  case true:
    x();
    break;
  default:
    if (x) {
      x();
    }
}
```

Bad output/actual:

```js
switch (x) {
  case true:
    x();
    break;
  default:
    if (x) {
      x();
  }
}
```

Note the closing brace of the IfStatement has bad indent.

This used to work, but regressed with b4dfb14a2ddaca8d1d5bc095f969f20c1114003a

**Comment by millermedeiros** [comment]
Did not try yet but looking at the commit that introduced regression it's probably the change I did to the `SwitchCase.getIndentEdges`

**Comment by jzaefferer** [comment]
:+1:
