### ISSUE TITLE
add command to check style

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/esformatter#292]
I was initially thinking on keeping this project as simple as possible and let other tools *derive* from it, but I think we should have our own `check` command (always be in sync with latest release). eg:

```sh
# check if file is formatted properly
esformatter check foo.js
```

ideally do something similar to what we do during the unit tests (highlight *expected* tokens as green and *actual* tokens as red) but displaying only the lines that have differences.

we should also add an option for [unified diff](http://en.wikipedia.org/wiki/Diff_utility#Unified_format) (with and without color) since other tools can consume this format and some terminals don't support color.

```sh
# unified diff without color
esformatter check --unified-no-color foo.js
```

the [diff](https://www.npmjs.com/package/diff) module is a good option.

**Comment by millermedeiros** [comment]
the funny thing is that [jscs](http://jscs.info/) started as a code style checker and is adding support to automatically format code and we started as a formatter and are planning to add features to check style :wink:

**Comment by jzaefferer** [comment]
My initial motivation when I got involved here was to build something like the style checking that jscs does. I now use both jscs and esformatter, one for checking, one for formatting. I still like the test output of esformatter - if that gets reduced to relevant lines, with annotated line and column numbers, but keeping the red/green actual/expected output, I'd try to use this in place of jscs, still.

**Comment by millermedeiros** [comment]
maybe @piuccio is interested in merging his work into esformatter itself (https://github.com/piuccio/esformatter-diff)

**Comment by millermedeiros** [comment]
I just wrote a tool to output pretty diffs: https://github.com/millermedeiros/disparity

![screenshot char diff](https://raw.githubusercontent.com/millermedeiros/disparity/master/chars_diff.png)

so now it should be very easy to integrate it into esformatter

**Comment by millermedeiros** [comment]
in the end it isn't a `check` command, but just a `--diff` and `--diff-unified` flags:

```sh
# check if "test.js" matches style and output diff to stdout
esformatter --diff test.js
# check if "test.js" matches style and output unified diff to stdout
esformatter --diff-unified test.js
# check if "test.js" matches "options.json" style and output diff to stdout
esformatter --diff --config options.json test.js
# check all files inside "lib/" and it's subfolders
esformatter --diff lib/**/*.js
```
