### ISSUE TITLE
move plugin documentation into an external file

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/esformatter#294]
too much information on the README, it scares people and make it harder to understand.

PS: wiki is not a good idea for documentation because of versioning.

**Comment by jzaefferer** [comment]
Next to `docs/plugins.md` you could also put a `docs/api.md` and extract the API section into that. Reduce the readme mostly to why/how, installation and CLI usage (with examples).

Also "Goals" section needs an update: Drop presets, mention plugins with link to related wiki page.
