### ISSUE TITLE
Mention Esprima Parser in README

### ISSUE THREAD

**Issue by Flet** [millermedeiros/esformatter#307]
One thing I struggled with in the beginning was the names of the hooks I want to change in my configuration.

This Esprina parser demo helped me understand what those hook names are: http://esprima.org/demo/parse.html

Maybe this is common information, but I found it enlightening and wish I had it at the start. Adding this to the README may help others who are just starting with this module.

**Comment by millermedeiros** [comment]
done! https://github.com/millermedeiros/esformatter/blob/master/doc/config.md#property-names

thanks for the feedback. I know the property names are crazy.
