### ISSUE TITLE
plugins should be able to list other plugins as dependencies

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/esformatter#308]
in some cases a plugin might depend on another plugin to do some special work (eg. https://github.com/millermedeiros/esformatter/issues/230#issuecomment-90803239) so we need a way to list sub-dependencies and execute these sub-dependencies somehow.

this is specially important for presets like `jquery` (#249) and `standard-format`.

**Comment by millermedeiros** [comment]
first idea that I had was to include an extra property on the plugin itself with the instances of the sub-plugins:

```js
// my-plugin.js
var quotes = require('esformatter-quotes');
var commas = require('esformatter-remove-trailing-commas');

exports.setOptions = function(opts) {
  opts.indent.value = '\t';
  if (opts.commas.removeTrailing) {
    // we can only edit the "sub" array inside setOptions
    exports.sub.push(commas);
    // if you add plugins here you need to call setOptions by yourself
    commas.setOptions(opts);
  }
};

// think of a better name for this
exports.sub = [
  quotes
];
```

and esformatter would call all `sub` plugins methods..

maybe we should even do `subBefore` and `subAfter` to allow granular control about the order the plugins are executed but it might be overkill.. I think in most cases plugin author would like the plugin methods to be executed *before* his own methods (so he can override the changes if needed).

**Comment by millermedeiros** [comment]
important to note that your plugin can already have sub dependencies without the special `sub` array, it's just more work:

```js
// my-plugin.js
var quotes = require('esformatter-quotes');

exports.setOptions = function(opts) {
  quotes.setOptions(opts);
  // ...
};

exports.tokenBefore = function(token) {
  quotes.tokenBefore(token);
  // ...
}; 
```

**Comment by jzaefferer** [comment]
Based on the examples above, the as-is doesn't look so bad. Is the abstraction really improving it?

**Comment by Nate-Wilkins** [comment]
@millermedeiros just as a side note the [eslintrc transformer](https://github.com/Nate-Wilkins/esformatter-transformer-eslintrc/blob/eee69dcad0a6faba7f4083fed4d825c356fd67ae/lib/index.js#L66-L68) isn't considered a plugin due to having each eslint rule depend on external esformatter plugins.

```js
var eslintrcTransformer = require('./eslintrc-transformer');

var options = eslintrcTransformer(esformatter, { /* eslintrc */ });

esformatter.format(/* some code */, options);
```
Which I guess is ok - but I would like to have it be an esformatter plugin for ease of use.

I'm not sure if I like the plugins requiring their own dependencies... Would using that same sub plugin at the configuration level have any negative side effects?

**Comment by millermedeiros** [comment]
right now plugins might have up-to 9 methods (`setOptions` > `stringBefore` > `transformBefore` > `tokenBefore` > `nodeBefore` > `nodeAfter` > `tokenAfter` > `transformAfter` > `stringAfter`) and each plugin is implemented in a different way.. so the extra abstraction would mean that you don't need to call all the methods and if the plugin API changes (eg. from `transformBefore` to `nodeAfter`) you don't need to update anything. - the disadvantage is that plugins that use the `sub` array won't work on old versions of esformatter.

if the plugin is written in the *proper way* they won't cause side-effects if executed multiple times over the same file, running `esformatter foo.js | esformatter | esformatter` produces the same output as running `esformatter foo.js` a single time. we should assume the user will only add extra plugins if his current settings doesn't do what he needs.

**Comment by Nate-Wilkins** [comment]
Good point. Does esformatter use the `setOptions` returns? Could return the `dependencies|sub` there instead of exporting them and having the dependencies only available after one `setOptions` is called.

**Comment by millermedeiros** [comment]
@Nate-Wilkins we don't use the return value, in fact the whole [plugin logic is pretty simple](https://github.com/millermedeiros/esformatter/blob/master/lib/plugins.js#L26-L29); we just loop through all the registered plugins and call the methods on each one of them passing the same arguments to all the plugins.

**Comment by millermedeiros** [comment]
this is somewhat related to the `extends` feature detailed on #328, so maybe it's unnecessary.. each plugin can do a single thing and presets can be listed using the `extends` (which in my opinion is way more *elegant*)

**Comment by millermedeiros** [comment]
ended up implementing a new `extends` feature, which can be used to create complex `plugins` and/or `presets`.

see https://github.com/millermedeiros/esformatter/issues/328#issuecomment-232618074 for more context
