### ISSUE TITLE
Blank line before first line comment

### ISSUE THREAD

**Issue by jzaefferer** [millermedeiros/esformatter#310]
For the jQuery preset (eventually plugin) I need a rule to have a blank line before every blank line, except if the previous line is also a line comment (so using `{ lineBreak.before.Linecomment: 2 }` won't work).

Is this something that can be part of esformatter itself? Or should it live in a plugin?

I currently have no clue how to implement this either way, since the setting mentioned above works, but I don't know how, since neither esformatter/lib nor rocambole-linebreak seem to have any specific rules about LineComment and linebreaks.

**Comment by millermedeiros** [comment]
maybe by adding a new `lineBreak.before.CommentGroup` setting?

line breaks and white spaces around comments are handled by [`postprocessToken` inside the `transform.js`](https://github.com/millermedeiros/esformatter/blob/master/lib/transform.js#L91-L107)

we could check if previous non-empty token is not a comment, and consider that as the group start.. and to grab the *group* end we check if next token is not a comment.
