### ISSUE TITLE
ES6: missing support for modules

### ISSUE THREAD

**Issue by 0x80** [millermedeiros/esformatter#311]
I am trying to use esformatter on a file which starts with an ES6 import declaration and it results in:

Error: Line 1: Unexpected token

If I remove that, if throws on the export. 

Am I missing something or are ES6 modules not supported at all?

**Comment by millermedeiros** [comment]
Esprima 2.1 don't support modules, we will replace the parser soon (https://github.com/millermedeiros/esformatter/pull/300) and implement the rules to format the module declaration.

Please keep this open so we can track the progress.


See #192

**Comment by RaitoBezarius** [comment]
Using the Espree branch, modules are formatted, but when I have this input:
```js
export const logger = new Logger;
```
It is formatted to:
```js
export
const logger = new Logger;
```

I don't think that this is the expected behavior, right?
It seems like that `esformatter` hook needs to check if the current assignement has a ExportSpecifier before.

**Comment by millermedeiros** [comment]
the `export` described above was fixed by https://github.com/millermedeiros/esformatter/commit/93aab2d98c7531e0d9e5a19d5d878d4f708eaeec but we still need to format all the possible `export` and `import` cases.

this post have some good examples: http://www.2ality.com/2014/09/es6-modules-final.html

and also: https://github.com/estree/estree/blob/master/es6.md#modules

**Comment by sircharleswatson** [comment]
I have the latest esformatter and i am still running into errors with es6 declarations

**Comment by millermedeiros** [comment]
@sircharleswatson please create a new issue with *input*, *output* and your *expected output*. the code is only as good as [the tests](https://github.com/millermedeiros/esformatter/blob/master/test/compare/default/module-in.js).

**Comment by sircharleswatson** [comment]
@millermedeiros Actually I realized it was an issue with using Node Modules within Meteor
