### ISSUE TITLE
ES6: export + shorthand object expression in class declarations

### ISSUE THREAD

**Issue by RaitoBezarius** [millermedeiros/esformatter#316]
Currently, esformatter isn't able to format correctly:
```js
export class Foobar extends EventEmitter {
  constructor(foo, bar, d = {}) {
    super();

    // foobar.
    var fooBar = {
      foo,
      bar
    };
  }
}
```

It seems like that it is due to ExportNamedDeclaration missing hook which prevents to format correctly those statements.

By the way, about `var fooBar = {foo, bar};`, I don't know if this is the expected behavior to be put on multiple lines, I think because those are shorthand, they can be put on the same line.

**Comment by millermedeiros** [comment]
@RaitoBezarius I see you did fix many bugs related to ES6 features and I just merged the espree branch, would like to submit pull requests for each of your commits? if you are too busy I can cherry-pick your commits (while keeping you as the author). plan to release v0.7.0 soon(ish) including as many fixes as possible.

**Comment by RaitoBezarius** [comment]
@millermedeiros No problem, I'll gladly open pull requests but I wasn't sure if you wanted to accept them ! :smile:
