### ISSUE TITLE
.esformatter file not found 

### ISSUE THREAD

**Issue by manuelodelain** [millermedeiros/esformatter#323]
My configuration : esformatter installed globally, a global config file .esformatter ($HOME).
I work on a different disk (partition) than the default one (where $HOME is located).
esformatter doesn't find the config file.

If I move the config file in the disk where I work esformatter finds the file and everything is ok.

**Comment by manuelodelain** [comment]
I think EsLint deals with that with the user-home module https://www.npmjs.com/package/user-home
https://github.com/eslint/eslint/blob/master/lib/config.js

`PERSONAL_CONFIG_PATH = userHome ? path.join(userHome, LOCAL_CONFIG_FILENAME) : null;`

**Comment by millermedeiros** [comment]
thanks for the bug report and for the `user-home` module suggestion
