### ISSUE TITLE
Wrong formatting of comments when they are next to a closing bracket

### ISSUE THREAD

**Issue by royriojas** [millermedeiros/esformatter#325]
Given the following input
```
var someFn = function() {
  // this will be fine
  someCodeHere();
  // this will not be aligned
}
```
We obtain the following output
```
var someFn = function() {
  // this will be fine
  someCodeHere();
// this will not be aligned
}
```
This only happens when the comment is next to a closing bracket.

This issue affects both line comments and block comments.

You can check the issue here using the latest esformatter.

http://requirebin.com/?gist=f5ba6fe754d5ba3d2b99

**Comment by millermedeiros** [comment]
this is in fact the expected behavior (see #209). you can change it by setting `indent.alignComments = false`

**Comment by royriojas** [comment]
I see! cool thanks
