### ISSUE TITLE
Format order for plugins

### ISSUE THREAD

**Issue by sircharleswatson** [millermedeiros/esformatter#326]
I am having an issue where esformatter makes a change to the line breaks before using the `esformatter-semicolon` plugin to add a semicolon.

Original Code:
```
var _originalEndWindow = BenchmarkWindows.findOne({benchmarkPeriodId: _targetBenchmarkPeriod._id})

                    var x1 = _aimLineData[0][0], y1 = _aimLineData[0][1]
                        , x2 = _originalEndWindow.endDate.valueOf(), y2 = _aimEnd[1]
                        , m = (y2 - y1) / (x2 - x1);
                    var x3 = _aimEnd[0], y3 = (m * (x3 - x1)) + y1;
```

Formatted Code
```
var _originalEndWindow = BenchmarkWindows.findOne({
                        benchmarkPeriodId: _targetBenchmarkPeriod._id
                    })                    var x1 = _aimLineData[0][0];
                    var y1 = _aimLineData[0][1];
                    var x2 = _originalEndWindow.endDate.valueOf();
                    var y2 = _aimEnd[1];
                    var m = (y2 - y1) / (x2 - x1);
                    var x3 = _aimEnd[0];
                    var y3 = (m * (x3 - x1)) + y1;
```

Because there is a missing semicolon the line breaks get removed first and it causes the app to crash. however, if I manually add in the semicolon first before reformatting, it works just fine.

So, it would be great if there was a way to add all the semicolons first. 

What do you think?

**Comment by twolfson** [comment]
Can you paste a copy of the config you are using so we can more easily reproduce/patch the issue?

**Comment by twolfson** [comment]
Config and plugins*

**Comment by sircharleswatson** [comment]
No problem!

```
{
    "root": true,
    "plugins": [
        "esformatter-semicolons",
        "esformatter-quotes",
        "esformatter-eol-last",
        "esformatter-spaced-lined-comment",
        "esformatter-remove-trailing-commas",
        "esformatter-var-each"
    ],
    "quotes": {
        "type": "double",
        "avoidEscape": true
    },
    "indent": {
        "IfStatement": 2,
        "ArrayExpression": 2,
        "AssignmentExpression": 2,
        "BinaryExpression": 2,
        "ConditionalExpression": 2,
        "CallExpression": 2,
        "CatchClause": 2,
        "DoWhileStatement": 2,
        "ForInStatement": 2,
        "ForStatement": 2,
        "FunctionDeclaration": 2,
        "FunctionExpression": 2,
        "MemberExpression": 2,
        "MultipleVariableDeclaration": 2,
        "ObjectExpression": 2,
        "ReturnStatement": 2,
        "SwitchCase": 2,
        "SwitchStatement": 2,
        "TopLevelFunctionBlock": 2,
        "TryStatement": 2,
        "VariableDeclaration.LogicalExpression": 2,
        "WhileStatement": 2
    },
    "line-break": {
        "keepEmptyLines": 2,

        "before": {
            "ArrowFunctionExpressionOpeningBrace": 0,
            "ArrowFunctionExpressionClosingBrace": ">=1",
            "EndOfFile" : 1,
            "ClassDeclarationOpeningBrace" : 0,
            "ClassDeclarationClosingBrace" : ">=1",
            "CatchOpeningBrace" : 0,
            "CatchClosingBrace" : ">=1",
            "DoWhileStatementOpeningBrace" : 0,
            "DoWhileStatementClosingBrace" : ">=1",
            "FinallyOpeningBrace" : 0,
            "FinallyClosingBrace" : ">=1",
            "ForInStatementOpeningBrace" : 0,
            "ForInStatementClosingBrace" : ">=1",
            "ForStatementOpeningBrace" : 0,
            "ForStatementClosingBrace" : ">=1",
            "FunctionExpressionOpeningBrace" : 0,
            "FunctionExpressionClosingBrace" : ">=1",
            "FunctionDeclarationOpeningBrace" : 0,
            "FunctionDeclarationClosingBrace" : ">=1",
            "IfStatementOpeningBrace" : 0,
            "IfStatementClosingBrace" : ">=1",
            "ElseIfStatementOpeningBrace" : 0,
            "ElseIfStatementClosingBrace" : ">=1",
            "ElseStatementOpeningBrace" : 0,
            "ElseStatementClosingBrace" : ">=1",
            "SwitchOpeningBrace" : 0,
            "SwitchClosingBrace" : ">=1",
            "TryOpeningBrace" : 0,
            "TryClosingBrace" : ">=1",
            "VariableName" : "2",
            "VariableValue" : 0,
            "VariableDeclaration" : "2",
            "VariableDeclarationWithoutInit" : "2",
            "WhileStatementOpeningBrace" : 0,
            "WhileStatementClosingBrace" : ">=1"
        }

    }
}
```

**Comment by twolfson** [comment]
Great, thanks! I will take a look at reproducing by the end of this weekend and then give you an ETA on patch (if it's on my end).

**Comment by sircharleswatson** [comment]
@twolfson Thanks a lot! We have a huge codebase at my company that is all over the place and esformatter _**almost**_ does the trick except for this issue :)

**Comment by sircharleswatson** [comment]
@twolfson If the knowledge helps, I don't run into any issues if I don't try to split the vars. I can run everything minus the var-each plugin and it works fine. it's just when I have both semicolons _**and**_ var-each running at the same time.

**Comment by twolfson** [comment]
It sounds like a whitespace issue being introduced by one of the plugins. Have to figure out which one though ;)

**Comment by sircharleswatson** [comment]
It definitely is a whitespace issue. I tried for about 6 or 7 hours yesterday to get it working but I only just learned about AST last night so I had no luck. I'll leave it to the pros haha

**Comment by twolfson** [comment]
If you are interested in learning more, thankfully JS is a small language so it's reasonable to pick up.

Here are some resources:

SpiderMonkey AST documentation: https://github.com/estree/estree/blob/4868ecf49900cc74d2d1a405ac8700c735949943/spec.md

Esprima source code (parser, tokenizer, and all): https://github.com/jquery/esprima/blob/2.2/esprima.js

Here are some repos I created while learning. I think I tried to document my thoughts/what was happening as much as possible:

https://github.com/twolfson/ecma-scopes

https://github.com/twolfson/ecma-variable-scope

**Comment by sircharleswatson** [comment]
I do know JS already. I'm a Meteor developer but I had never heard of AST.

**Comment by twolfson** [comment]
I have began to take a look at triaging the issue. I have successfully set up a gist to reproduce the issue here:

https://gist.github.com/twolfson/0d76da04b19870c6ab1f/0246eb580a4484ad2c8bf4abe9dad25dda361e86#file-readme-md

**Comment by twolfson** [comment]
I have reduced the issue to its minimal case.

```js
var hello
  var world
```

to:

```js
var hello  var world
```

with a config of:

```
{
    "plugins": [
        "esformatter-var-each"
    ]
}
```

https://gist.github.com/twolfson/0d76da04b19870c6ab1f/60c8fa91487ac75b4d365a054deedb506a392075

The issue is within `esformatter-var-each` so this issue can probably be closed. Since we know the source, let's do all future correspondence in:

https://github.com/twolfson/esformatter-var-each/issues/2

**Comment by sircharleswatson** [comment]
Sounds good!
