### ISSUE TITLE
`extends` like ESLint

### ISSUE THREAD

**Issue by vvo** [millermedeiros/esformatter#328]
ESLint has a neat feature called shareable configurations: http://eslint.org/docs/user-guide/configuring#extending-configuration-files

Basically this would allow to have an `.esformatter` that would look like:

```json
{
  "extends": ["esformatter-config-airbnb", "esformatter-config-algolia"]
}
```

That would load the `node_modules/esformatter-config-airbnb/index.js` and extends it with `node_modules/esformatter-config-algolia/index.js`

What do you think?

**Comment by vvo** [comment]
Shareable config doc: http://eslint.org/docs/developer-guide/shareable-configs

**Comment by millermedeiros** [comment]
sounds like a good feature. right now you can do it by converting your config into a `plugin` and using the [setOptions](https://github.com/millermedeiros/esformatter/blob/master/doc/plugins.md#setoptionsoptions)

```js
var deepFillIn = require('mout/object/deepFillIn');
exports.setOptions = function(opts) {
  deepFillIn(defaultAndUserOptions, pluginOptions);
};
```

but I agree that having a simple `module.exports = myPresetOptions;` is way more user friendly, specially if the preset depends on other plugins.. (plugin registration happens before the `setOptions` call, so adding other plugin to the `plugins` array won't have any effect).

see: #249

**Comment by millermedeiros** [comment]
Babel presets is also a nice solution: https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md#making-your-own-preset

I'll try to work on this next month, been delaying for too long.

**Comment by millermedeiros** [comment]
finally had the time to work on this. Still need to update the documentation, but basically:

```js
{
  "extends": [
    "preset:foobar", // load "esformatter-preset-foobar" from "./node_modules"
    "./lorem_ipsum.json" // load relative config file
  ]
}
```

and presets, can extend other presets and register plugins:

```js
// need to use `require` because dependencies will be listed
// on the preset "package.json"
module.exports = {
  extends: [
    require('esformatter-preset-dolor')
  ],
  plugins: [
    require('esformatter-quotes')
  ]
};
```

this should also close #308
