### ISSUE TITLE
Semicolon format

### ISSUE THREAD

**Issue by kewah** [millermedeiros/esformatter#334]
Hej,
Semicolons don't seem to be formatted.
http://requirebin.com/embed?gist=0d67452e01754269660f

Input:
```js
var a = 'foo'                ;
var b = '3'
  ;
```

Current: 
```js
var a = 'foo'                ;
var b = '3'
  ;
```

Expected:
```js
var a = 'foo';
var b = '3';
```

Tested with v0.7.1 and default settings.

Thanks

**Comment by millermedeiros** [comment]
I think on `VariableDeclaration` it's "safe" to assume nobody would want white spaces before the `;` but I'm not sure if we can remove the line breaks in all cases, eg:

```js
// comma-first + asi
var foo = 123
  , bar = 456
;[1,2,3].forEach(echo)
```

are there any other cases that you saw this happening or just the `VariableDeclaration`?

**Comment by bulyshko** [comment]
@millermedeiros I believe this is happening only for the `VariableDeclaration`.
