### ISSUE TITLE
Support user-defined presets (or similar extension functionality)

### ISSUE THREAD

**Issue by wbinnssmith** [millermedeiros/esformatter#335]
In a similar way to how [eslint supports extending other user-defined configurations](http://eslint.org/docs/user-guide/configuring.html#extending-configuration-files), it would be awesome if esformatter presets weren't limited to the two defined inside of esformatter itself.

This could leverage the existing preset functionality, or possibly be called extend[s] to indicate the nature of it. The value for this field could be resolved in a similar fashion as `require.resolve`.

**Comment by wbinnssmith** [comment]
Closing since this is a dupe of #328

**Comment by millermedeiros** [comment]
just a FYI, our idea is to remove the jquery preset from the lib (so we would only have the default rules and all the presets would be stored as external dependencies)

**Comment by wbinnssmith** [comment]
Love the idea!

I wonder if it's worth having another  preset that if basically a no-op, so
esformatter can be entirely unopinionated to start, making all rules
explicit and opt-in. If I remember correctly eslint was making this the
default in a future version.

**Comment by millermedeiros** [comment]
I also wanted a no-op preset, but that is too hard to implement.. we still make some changes to the original indentation and the position of commas/semicolons even if all options are set to `-1` (see #113)

there are so many edge cases and some things are simpler to implement without caring about the original formatting.

**Comment by millermedeiros** [comment]
FYI, this was implemented last night! https://github.com/millermedeiros/esformatter/issues/328#issuecomment-232618074
