### ISSUE TITLE
Confused by ES6 class syntax

### ISSUE THREAD

**Issue by 0x80** [millermedeiros/esformatter#337]
The formatter can handle this fine:

```javascript
var Creditcards = React.createClass({
```

but this
```javascript
class Creditcards extends React.Component {
```

becomes
```javascript
class Creditcards extends React . Component {
```

I work around this by using Component directly, but I assume this is a bug.

**Comment by 0x80** [comment]
I found another far more annoying bug with class formatting. This time I can't find a way to work around it :'(

```javascript
export default class ActiveMeeting extends Component {
  renderAttendees() {
    return this.props.meeting.attendees.map((attendee) => {
      return <Attendee key={attendee.displayName} profile={attendee}/>
    })
  }
}
```

turns into

```javascript
export default class ActiveMeeting extends Component {
  renderAttendees() {
    return this.props.meeting.attendees.map((attendee) => {
      return <Attendee key={attendee.displayName} profile={attendee}/>
      })
    }
  }
```

The indentation is messed up, and my linter wont accept that of course. I use the standard-format on file save and because of this I will have to switch it off and manually correct whitespace style.

also

```javascript
export default class App extends Component {
  constructor(props) {
  }
}
```
turns into

```javascript
export default class App extends Component {
  constructor( props) {
  }
}
```
Notice the extra whitespace before props. The JSS linter will complain about this too.

And similarly

```javascript
export default class App extends Component {
  myfunction () {
  }
}
```
... turns into 

```javascript
export default class App extends Component {
  myfunction() {
  }
}
```

Also not compatible with JSS standard.

**Comment by webcarrot** [comment]
Semicolons?
```javascript
export default class ActiveMeeting extends Component {
  renderAttendees() {
    return this.props.meeting.attendees.map((attendee) => {
      return (<Attendee key={attendee.displayName} profile={attendee}/>);
    });
  }
}
```

**Comment by 0x80** [comment]
What about semicolons?

**Comment by 0x80** [comment]
I just found out that the format issues in the second examples that I've posted are not esformatters fault. They are introduced by [standard-format](https://github.com/maxogden/standard-format).

This is a formatter based on this [standard](https://github.com/feross/standard). And I'm very happy that they decided to ditch semicolons btw ;)

**Comment by millermedeiros** [comment]
the indent on the return is actually because of JSX, not the lack of semicolons, this works just fine:

```js
export default class ActiveMeeting extends Component {
  renderAttendees() {
    return this.props.meeting.attendees.map((attendee) => {
      return attendee.displayName
    })
  }
}
```

lets open individual bugs for each issue, that way it's easier to track progress.

**Comment by 0x80** [comment]
[Here](http://requirebin.com/?gist=a8d74c612f35f3af3615) I've used the current standard-format whitespace rules to highlight a few problems with es6 related syntax. The destructuring assignment is just a esformatter setting I suppose. The others I can't solve.

**Comment by vvo** [comment]
> but this
> 
> class Creditcards extends React.Component {
> becomes
> 
> class Creditcards extends React . Component {

I can confirm this bug, is there already another issue tracking this or a fix incoming? I cannot find it
