### ISSUE TITLE
ObjectPatternComma messes up ES6 destructuring assignment

### ISSUE THREAD

**Issue by 0x80** [millermedeiros/esformatter#342]
```javascript
const {Group, Surface} = ReactArt
```

becomes

```javascript
const {Group , Surface} = ReactArt
```

**Comment by 0x80** [comment]
What is this setting supposed to do anyway? I can't seem to figure it out

**Comment by millermedeiros** [comment]
the setting is supposed to allow user to limit how many white spaces and line breaks around the comma.

I just tested with the default settings on v0.7.2 and it works as expected.. see tests here: [input](https://github.com/millermedeiros/esformatter/blob/master/test/compare/default/object_pattern-in.js) and [output](https://github.com/millermedeiros/esformatter/blob/master/test/compare/default/object_pattern-out.js)

**Comment by millermedeiros** [comment]
`whiteSpace.before.ObjectPatternComma = whiteSpace.after.ObjectPatternComma = 1`:

```js
const {Group , Surface} = ReactArt
```

---

`whiteSpace.before.ObjectPatternComma = whiteSpace.after.ObjectPatternComma = 0`:

```js
const {Group,Surface} = ReactArt
```

**Comment by 0x80** [comment]
Thanks I get it now. I got confused by the standard-format esformatter settings, we regular objects were not affected by this setting somehow.

**Comment by millermedeiros** [comment]
regular objects are affected by `Property`, `PropertyName` and `PropertyValue`
