### ISSUE TITLE
ES7 feature format

### ISSUE THREAD

**Issue by kenokabe** [millermedeiros/esformatter#345]
Sometimes, we want to write a code using ES7 feature, such as in React-JSX code.

```
class ContentComponent extends React.Component {
     handleChange = (e)=> {
  
      //........
  
     };
//........
}
```

like Babel Stage:0 or State:1 mode.

I use ESLint for this code with no problem, however, with esformater, currently, I cannot find an option to do so, and an error occurred as the invalid code.

If there's any work-around, please let me know, and also I'd like to list this issue as a feature-request.

Thanks!

**Comment by millermedeiros** [comment]
we currently use the `espree v1.x` and they don't have plans to support experimental features.

there is no need for the arrow function on your example, this works just fine:

```js
class ContentComponent extends React.Component {
  handleChange(e) {
    // ...
  }
}
```

you are probably using the `babel-eslint` since `eslint` itself also uses `espree` to parse the file (and would throw an error on the `=` sign).

going to close this for now but feel free to reopen if this feature becomes a standard.

**Comment by kenokabe** [comment]
Thanks, @millermedeiros 

You are right, and the reason I had to do what I did is, with the way you suggested, we must bind the entire method in the constructor. Therefore I avoided.

ref.
https://github.com/SimonDegraeve/react-class-helper

So, now, I add some base Component for auto-biding mechanism referring the above.

```
class Component extends React . Component {

    constructor(props) {
      super(props);
      this.autoBind();
    }

    // Bind an array of method name to class instance
    bind(methods) {
      methods.forEach(method => {
        this[method] = this[method].bind(this);
      });
    }

    // Bind all methods to class instance
    autoBind() {
      this.bind(
        Object.getOwnPropertyNames(this.constructor.prototype)
          .filter(prop => typeof this[prop] === 'function')
      );
    }
  }


```

Just for note. Thanks for your suggestion again.

Regards.
