### ISSUE TITLE
Error: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by excelle08** [millermedeiros/esformatter#352]
My ESFormatter failed to work today, complaining 'Error: ENOENT, No such file or directory':
![error](https://cloud.githubusercontent.com/assets/9147467/9424018/622a0b42-490f-11e5-9189-641bbc9ebc93.png)

What could cause this error? Is it problems with the code I wrote or the plugin itself?
PS: ESFormatter-jsx is installed.

**Comment by millermedeiros** [comment]
the problem should probably be on the editor plugin, and not esformatter itself (but I might be wrong)

**Comment by excelle08** [comment]
@millermedeiros I just press the save button and ESFormatter triggers that message. 
Yes. It happens with all files, with no syntax mistakes.

**Comment by millermedeiros** [comment]
closing since problem is probably on the editor plugin itself or something else on the user environment.
