### ISSUE TITLE
Support for experimental object spread operator

### ISSUE THREAD

**Issue by glifchits** [millermedeiros/esformatter#353]
Hi there! I'm getting the following error:

```
Error: app/MyComponent.jsx:336 Unexpected token ...
```

The offending line 336 is:
```javascript
var { type, parties, sentences, ...props } = this.props;
```

I've got the esformatter-jsx plugin installed and thats it.

In case you're not sure what I'm referring to, see more about the ES6 spread operator here: http://babeljs.io/docs/learn-es2015/#default-rest-spread

**Comment by glifchits** [comment]
Looks like Espree is not supporting this: https://github.com/eslint/espree/issues/116

**Comment by millermedeiros** [comment]
latests espree supports `ObjectRestSpread`. see: #349 and https://github.com/eslint/espree/issues/163

**Comment by glifchits** [comment]
Cool! Is #351 going to be merged in soon? :)

**Comment by thenikso** [comment]
I'm still getting `Cannot read property 'startToken' of undefined` on a file containing something like:

```
cons a = { ...b };
```

with v0.8.1. Am I doing something wrong?
