### ISSUE TITLE
Missing Support for ES7 Class Properties

### ISSUE THREAD

**Issue by tommmyy** [millermedeiros/esformatter#354]
input

```
class MyDiv{
         static            
propTypes = {
      // default props
       };

  render() {
    return <div>My div</div>
  }
}
```

expected
```
class MyDiv{
  static propTypes = {
      // default props
  };

  render() {
    return <div>My div</div>
  }
}
```

**Comment by millermedeiros** [comment]
@tommmyy for now we can only support features that are implemented by [espree](https://github.com/eslint/espree). which doesn't support experimental features so far.

going to close and mark as invalid until we replace the parser or this feature becomes at least `Stage 3 - Candidate`

**Comment by millermedeiros** [comment]
see also #345
