### ISSUE TITLE
ES6 for of support

### ISSUE THREAD

**Issue by MiincGu** [millermedeiros/esformatter#356]
When writting for of like this:

```javascript
for (var item of array) {
  doSomething();
}
```

after format, I always got this:
```javascript
for (
var item of array) 
{
doSomething();
}
```

but what I want is don't change it.

**Comment by millermedeiros** [comment]
this is probably a conflict between the `VariableDeclaration` and the `for`..

**Comment by TommyM** [comment]
Any news on this issue?

**Comment by millermedeiros** [comment]
did not have time to work on this but should be an easy fix. the `for` should be able to undo the line breaks. just need to check if the expression is a `var of` before doing it.

**Comment by TommyM** [comment]
I have it working locally by basically just copying all the logic for the ForInStatement. Some parts (for for...in as well) are not the cleanest, but it works.

**Comment by TommyM** [comment]
PR for this at #365

**Comment by millermedeiros** [comment]
thanks a lot @TommyM !!! just landed your PR.

**Comment by dnascimento** [comment]
The bug still exists:
```
for(let x of array){}
```
