### ISSUE TITLE
Arrow function indentation appears to be incorrect

### ISSUE THREAD

**Issue by ckknight** [millermedeiros/esformatter#357]
Given an indent of 2, I'm receiving the following result:

```js
const object = x => ({
    x
});

const retObject = x => {
  return {
    x
  };
}

const array = x => [
    x
];

const callWithObject = x => f({
    x
  });
```

My expectation:

```js
const object = x => ({
  x
});

const retObject = x => {
  return {
    x
  };
}

const array = x => [
  x
];

const callWithObject = x => f({
  x
});
```

As you can see, the only one that was correct was `retObject`, the rest having unexpected indentation (that eslint then yells at me about).

**Comment by doque** [comment]
I can report another weird indentation case when using arrow function in lodash's `_.some()`:

http://requirebin.com/embed?gist=0d67452e01754269660f#%7B%22config%22%3A%7B%22jsx%22%3A%7B%22attrsOnSameLineAsTag%22%3Afalse%2C%22maxAttrsOnTag%22%3A1%2C%22firstAttributeOnSameLine%22%3Afalse%2C%22alignWithFirstAttribute%22%3Atrue%7D%7D%2C%22code%22%3A%22%5Cnconst%20classNames%20%3D%20%5B%5C%22a%5C%22%2C%20%5C%22b%5C%22%2C%20%5C%22c%5C%22%5D%3B%5Cn%5Cnexport%20default%20class%20TimeoutModal%20%7B%5Cn%20%20%5Cn_isA()%20%7B%5Cnlet%20classNames%20%3D%20document.body.className.split(%5C%22%20%5C%22)%3B%5Cn%5Cn%20%20return%20_.some(classNames%2C%20(className)%20%3D%3E%20%7B%5Cn%5Cn%20%20%20%20return%20className%20%3D%3D%3D%20%5C%22a%5C%22%3B%5Cn%20%20%20%20%5Cn%20%20%7D)%20%3D%3D%3D%20false%3B%5Cn%20%20%5Cn%7D%5Cn%5Cn%5Cn%7D%5Cn%22%7D
