### ISSUE TITLE
Returning a class indents the last brace

### ISSUE THREAD

**Issue by ckknight** [millermedeiros/esformatter#358]
Actual:
```js
function makeClass() {
  return class MyClass {
    method() {}
    };
}
```

Expected:
```js
function makeClass() {
  return class MyClass {
    method() {}
  };
}
```

As you can see, the brace (`}`) closing the class is unnecessarily indented.

**Comment by craigrich** [comment]
+1

**Comment by jonny-improbable** [comment]
This issue also affects the default pattern for implementing a multiline `render()` method in a React component, eg:

Expected:
```javascript
class Foo {
  render() {
    return (
      <Foo/>
    )
  }
}
```

Actual:
```javascript
class Foo {
  render() {
    return (
      <Foo/>
      )
  }
}
```

I knocked up a test-case and started trying to debug it inside the `hooks` folder; any pointers would be very useful (:
