### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by DaleJefferson** [millermedeiros/esformatter#364]
Example flow file
```
/* @flow */
function foo(x: string, y: number): string {
  return x.length * y;
}
foo('Hello', 42);
```

http://flowtype.org

**Comment by millermedeiros** [comment]
we use [espree](https://github.com/eslint/espree) to parse the files, so we can't really add support for flow unless we replace the parser..

marking it as wontfix for now, but maybe in he future we can reopen if more people asks for it and/or we change the way the formatting works.

**Comment by drewhamlett** [comment]
This would be great.  Thanks!

**Comment by arypurnomoz** [comment]
+1

**Comment by millermedeiros** [comment]
reopening since I'm planning to replace the parser to use babylon (#398) which would allow us to implement this as a plugin.

**Comment by millermedeiros** [comment]
BTW, I started the plugin development 2h hours ago and got a good chunk of it done already. Should publish it later today or over the weekend. But it will only work if esformatter is using babylon + accorn-to-esprima.

**Comment by millermedeiros** [comment]
Flow plugin implemented with basic features (https://github.com/millermedeiros/esformatter-flow), now just need to release `esformatter@0.9.0` and publish both to npm.
