### ISSUE TITLE
Function names are not formatted properly in es6 object shorthand

### ISSUE THREAD

**Issue by tweettypography** [millermedeiros/esformatter#368]
From what I can tell, when using the new es6 object literal shorthand syntax for function declarations the formatter seems to be formatting as if the function is being invoked, rather than declared. For example:

```
{
    foo () {
    }
}
```

Which (regardless of your options for functionreservedword & functioname) gets reformatted as:

```
{
    foo() {
    }
}
```

**Comment by millermedeiros** [comment]
just added `whiteSpace.after.MethodName = 1` support, will release new version soon including this.

PS: methods inside classes are configured through `whiteSpace.after.MethodDefinitionName` (introduced on https://github.com/millermedeiros/esformatter/commit/23c15ad2db479bc57eca546b49a3215f4834e631)

**Comment by ericalas93** [comment]
Hey, sadly I'm still running into this issue :( 


`const actions = {
        someaction( param ) { //no space after someaction 
        return {
           //
        };
    },
};`

here is my config:
`{
"whiteSpace" : {
"before" : {
      //some settings
    },
    "after" : {
      "MethodName": 1
    }
  }
}`

any ideas? is it possible other settings are somehow overriding it? 

Thanks! i love esformatter, its really easy to config :)
