### ISSUE TITLE
lines combined when one ends with [] (square brackets) within a function

### ISSUE THREAD

**Issue by focusaurus** [millermedeiros/esformatter#369]
Given this sample input, the top-level snippets are left alone properly, but the 2 statements within the function are erroneously combined into one line.

**input**
```js
var fine = process.argv[0]
var noprob = 2

function blah () {
  var oops = process.argv[0]
  var goestolineabove = 2
}
```

**output with bug** (no longer valid JS)
```js
var fine = process.argv[0]
var noprob = 2

function blah () {
  var oops = process.argv[0]var goestolineabove = 2
}
```

esformatter version 0.7.3

**Comment by millermedeiros** [comment]
already fixed on master. not sure which commit fixed it tho.. I guess it should be #334. thanks for reporting!
