### ISSUE TITLE
Missing indent of comment at the end of a block

### ISSUE THREAD

**Issue by akloeber** [millermedeiros/esformatter#371]
If the last line of a block contains a comment (line or block) it is not indented on the same level as the rest of the function body:

INPUT:
```
if (a > 0) {
  // a
  console.log('bar');
  // b
}
```

OUTPUT:
```
if (a > 0) {
  // a
  console.log('bar');
// b
}
```

esformatter v0.7.3 (default config)

**Comment by millermedeiros** [comment]
that's by design, see https://github.com/millermedeiros/esformatter/issues/325#issuecomment-115801190
