### ISSUE TITLE
Line break after comma of unset variables

### ISSUE THREAD

**Issue by Asuza** [millermedeiros/esformatter#382]
I don't know if this is not yet implemented or I just can't figure out the right config. I've been finding which configs I need by typing sample code into the [Esprima Parser](http://esprima.org/demo/parse.html), then searching the esformatter module for the types that show up.

I have this:
```javascript
function getInverseAnswer() {
  var a = 10,b=4,answer,inverse;
  answer = a * b + (a - b - b);
  inverse = answer * -1;
  return inverse;
}
```

Which gets turned into:
```javascript
function getInverseAnswer () {   
    var a = 10,                  
        b = 4,                   
        answer, inverse;         
                                 
    answer = a * b + (a - b - b);
    inverse = answer * -1;       
                                 
    return inverse;              
}
```

Via the following config: 
```json
{
  "indent": {
    "value": "    "
  },
  "lineBreak": {
    "before": {
      "ArrayExpressionClosing": 1,
      "ReturnStatement": 2
    },
    "after": {
      "ArrayExpressionComma": 1,
      "ArrayExpressionOpening": 1,
      "ForStatementClosingBrace": 2,
      "VariableDeclarationSemiColon": 2,
      "VariableValue": 1
    }
  },
  "whiteSpace": {
    "value": " ",
    "removeTrailing": 1,
    "before": {
      "ArrayExpressionClosing": 0,
      "ArrayExpressionOpening": 0,
      "MemberExpressionClosing": 0
    },
    "after": {
      "ArrayExpressionOpening": 0,
      "FunctionName": 1,
      "FunctionReservedWord": 1,
      "IfStatementConditionalOpening": 0,
      "MemberExpressionOpening": 0,
      "ObjectExpressionClosingBrace": 1
    }
  }
}
```

However, I would like `answer` and `inverse` to be on separate lines. I think this would be called `VariableDeclarator` or `VariableDeclaratorComma`, but I've no real clue. Is it possible to do currently?

**Comment by millermedeiros** [comment]
we had a setting called `VariableDeclarationWithoutInit` but [I deleted it by mistake](https://github.com/millermedeiros/esformatter/commit/e7b465e63676972fad3ed7b4bfa0fe54cffe314d#diff-6fcd8cc1d7528989bae482487b286f7eL35) some time ago..

we should definitely re-implement this feature. it's still [part of the default preset](https://github.com/millermedeiros/esformatter/blob/425fc93381565893c33520f4a5346aa97a3aebdb/lib/preset/default.json#L142) and we should not remove the line breaks by default.

**Comment by millermedeiros** [comment]
marking this as a bug so it gets fixed on the next release (should be easy to fix, PRs are welcome).

**Comment by millermedeiros** [comment]
re-enabled the `VariableDeclarationWithoutInit` support. so now this should work as expected by default.
