### ISSUE TITLE
AssignmentExpression value doesn't seem to be reacting

### ISSUE THREAD

**Issue by nmaxcom** [millermedeiros/esformatter#390]
Whatever value I put in AssignmentExpression (locally or [in the live preview](http://requirebin.com/embed?gist=0d67452e01754269660f)) doesn't seem to have an effect on variable assignments such as:
`var seguimos = true, letra = '', speed = 100, rndblock = 4, delay = 0, caret = '▌', caretOff = '࿍', caretOn = true, textoOrig = $(selector).text(), texto = $(selector).text(), escrito = caret;`

I like its default behaviour:

```
var seguimos = true,
        letra = '',
        speed = 100,
        rndblock = 4,
        delay = 0,
        caret = '▌',
        caretOff = '࿍',
        caretOn = true,
        textoOrig = $(selector).text(),
        texto = $(selector).text(),
        escrito = caret;
```

...but there's no say into that it seems.

**Comment by millermedeiros** [comment]
can you elaborate better which property did you try to set? the example above is handled by `VariableDeclaration`; which is handled by: https://github.com/millermedeiros/esformatter/blob/master/lib/hooks/VariableDeclaration.js

**Comment by millermedeiros** [comment]
closing since I don't know what is wrong. feel free to reopen and/or add more comments i problem persists.
