### ISSUE TITLE
Error message doesn't include file name

### ISSUE THREAD

**Issue by kjk** [millermedeiros/esformatter#394]
```
$ ./node_modules/.bin/esformatter -i js/*js*
Unexpected token (15:22)
```

Without file name, the error message is not helpful.

```
$ ./node_modules/.bin/esformatter -v
esformatter v0.8.1
```

**Comment by millermedeiros** [comment]
I changed the way we handle error messages on v0.9.0: https://github.com/millermedeiros/esformatter/blob/c77d9942ca2fe7d1b954dad109ebe9601022484d/lib/cli.js#L111-L123 - so now you should see a clear message - test: https://github.com/millermedeiros/esformatter/blob/c77d9942ca2fe7d1b954dad109ebe9601022484d/test/cli.spec.js#L224-L225

please reopen if the error persists.
