### ISSUE TITLE
do while without closing semi breaks indentation

### ISSUE THREAD

**Issue by soldair** [millermedeiros/esformatter#401]
trying to figure out how to fix it but making an issue to track it and for help =)

input.js
```
do {
  console.log('hi')
} while (0)

if ('hi') {
  console.log(1)
}
```

result `esformater input.js`

```
do {
  console.log('hi')
} while (0)

  if ('hi') {
    console.log(1)
  }
```

**Comment by soldair** [comment]
this only happens when a function is called in the body of the dowhile.

**Comment by soldair** [comment]
this effectively stops anyone from being able to use do while in standard who depend on standard-format

**Comment by millermedeiros** [comment]
logic is handled by this file: https://github.com/millermedeiros/esformatter/blob/master/lib/hooks/DoWhileStatement.js - pull requests are highly appreciated! I won't have time to work on this until the weekend.

**Comment by millermedeiros** [comment]
problem is on the `getIndentEdges` logic, it should probably check if `node.endToken.value === ')'` before trying to find the previous `)`.

**Comment by soldair** [comment]
I'm still trying to grok how everything really works but ill give it a shot =). thank you so much for the pointers.
