### ISSUE TITLE
Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by jwaldrip** [millermedeiros/esformatter#408]
Getting the following error when trying to run esformatter on this file: https://github.com/brandfolder/graphqlify/blob/develop/graph/typeHelpers.js

`Cannot read property 'value' of undefined`

**Comment by millermedeiros** [comment]
Is that the only message that you get? No stack trace or anything else?

**Comment by jwaldrip** [comment]
Correct


- Jason

-----

Jason Waldrip
Chief Technology Officer
Brandfolder.com
email| jason.waldrip@brandfolder.com
office |720-744-0311(tel:720-744-0311)
mobile |646-460-5959(tel:646-460-5959)

**Comment by stevenp** [comment]
I'm getting the same error on a file of mine, and it seems to be related to not having a semicolon at the end of the export line. If you add one, the error goes away. Hopefully this helps you track down why it's failing.

**Comment by millermedeiros** [comment]
v0.9.2 includes this fix! thanks for the bug report!

**Comment by jwaldrip** [comment]
Thanks!

> On Feb 27 2016, at 10:03 pm, Miller Medeiros
&lt;notifications@github.com&gt; wrote:  

>

> v0.9.2 includes this fix! thanks for the bug report!

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/millerm
edeiros/esformatter/issues/408#issuecomment-189784001).![](https://github.com/
notifications/beacon/AAConLZ4RVqMi-Qfxg88UdQYac5OQX1sks5ponclgaJpZM4HZ_SQ.gif)
