### ISSUE TITLE
Add column length config prop

### ISSUE THREAD

**Issue by granteagon** [millermedeiros/esformatter#409]
This might be a rather lengthy change, but it would be great to have a line length property that would reformat sections of code that go over the limit.

Currently if my Ruler in sublime is set to 78, and I do a declaration like this:
```es6
    const {
      index, label, connectDropTarget, isOver, canDrop, onClick
    } = this.props
```

The formatter will break reformat the code to something that goes over my ruler setting:
```es6
    const {index, label, connectDropTarget, isOver, canDrop, onClick} = this.props
```

**Comment by millermedeiros** [comment]
I would love to see this feature implemented.. but I'll leave it to a plugin, similar to [esformatter-collapse-objects](https://github.com/wbinnssmith/esformatter-collapse-objects)

adding this feature directly to esformatter would increase the complexity drastically and I'm trying to limit the scope of the project.

I updated the wish list on the wiki to include a link to this issue: https://github.com/millermedeiros/esformatter/wiki/Plugins#wish-list

**Comment by millermedeiros** [comment]
PS: setting options to `-1` will keep the existing line breaks; so you can set `lineBreak.after.ObjectPatternComma = -1`, `lineBreak.after.ObjectPatternOpeningBrace = -1` and `lineBreak.before.ObjectPatternClosingBrace = -1` to bypass the automatic line break removal...

**Comment by pgelinas** [comment]
FYI, I've written a plugin that should take care of this. It still a very early piece of work, but it handles the cases that I needed it to. Check it out: https://github.com/pgelinas/esformatter-auto-wrap
