### ISSUE TITLE
IIFE's content incorrectly indented

### ISSUE THREAD

**Issue by JonathanWolfe** [millermedeiros/esformatter#410]
The contents of IIFE's are incorrectly indented by -1 indent.

**Example:**
```js
/**
 * Esformatter Indenting
 */
( function initParser() {
return parser;
}() );

/**
 * Correct Indenting
 */
( function initParser() {
	return parser;
}() );
```

**Comment by millermedeiros** [comment]
uhm, I was not able to reproduce this on the latest version with the default settings - I copied the example and did `pbpaste | ./bin/esformatter | pbcopy` and this is the output I got:

```js
/**
 * Esformatter Indenting
 */
(function initParser() {
  return parser;
}());

/**
 * Correct Indenting
 */
(function initParser() {
  return parser;
}());
```

make sure you have [`indent.TopLevelFunctionBlock: 1` in your settings](https://github.com/millermedeiros/esformatter/blob/0890e0aa73b7b8343ea500b7aaa75e7aa4e61eba/lib/preset/default.json#L46)

feel fee to reopen if problem persists and/or if you have another test case.

PS: this logic is handled here: https://github.com/millermedeiros/esformatter/blob/769a1816b86f0c4154ef532133527ad4ef57090d/lib/hooks/FunctionExpression.js#L44-L57

**Comment by JonathanWolfe** [comment]
Yep, sorry. I was on the "jQuery" preset.
