### ISSUE TITLE
Indent content inside return parentheses

### ISSUE THREAD

**Issue by DaleJefferson** [millermedeiros/esformatter#412]
input and expected output:

```
function hello() {
    return (
        'Hello'
    );
}
```

current output (v0.9.1):

```
function hello() {
    return (
    'hello'
    );
}
```

@millermedeiros kindly fixed this issue with arrow functions in #399 it would be great to do the same in this example.

This is a very popular pattern for React.

```
class Hello extends React.Component {
    render() {
        return (
             <h1>Hello</h1>
        );
    }
}
```

**Comment by DaleJefferson** [comment]
It looks like this is already supported, I changed 
```
"indent" : {
    "ReturnStatement": ">=1"
}

// to

"indent" : {
    "ReturnStatement": "1"
}
```

And it seems to do the right thing in my initial testing.

**Comment by millermedeiros** [comment]
`lineBreak` is the only one that accepts `>=1`.. Indent and white space only works with integers.

We should probably open a new task to validate the options and warn users about wrong values.

**Comment by DaleJefferson** [comment]
@millermedeiros I copied my config from standard-format

https://github.com/maxogden/standard-format/blob/master/rc/esformatter.json
