### ISSUE TITLE
Add a space after a function declaration identifier

### ISSUE THREAD

**Issue by pmcelhaney** [millermedeiros/esformatter#425]
Given a function declaration:

```
function foo() {
  return 'bar';
}
```

I want to add a space between the function name and the parentheses.

```
function foo () {
  return 'bar';
}
```

Is there a configuration that would allow me to do that now? Here's what I've tried:

```
  "esformatter": {
    "whitespace": {
      "before": {
        "ParameterList": 1
      }
    }
  }
```

If the code doesn't support such a setting now, any ideas on how to add it? I poked around the code and it looks like it may have something to do with FunctionDeclaration.js, Params.js, or both.

**Comment by pmcelhaney** [comment]
Or how would I go about writing a plugin?

**Comment by millermedeiros** [comment]
the setting that you are looking for is [`whiteSpace.after.FunctionName = 1`](https://github.com/millermedeiros/esformatter/blob/27d2f1af80e0cdca33facff86c50d4218f4137fb/lib/hooks/FunctionDeclaration.js#L11)
