### ISSUE TITLE
Removes line break before 'else if' after statement

### ISSUE THREAD

**Issue by larsch** [millermedeiros/esformatter#426]
```js
if (foo)
   bar();
else if (baz)
   done();
```

Running `esformatter elseif.js`:

```js
if (foo)
   bar();else if (baz)
   done();
```

```sh
$ esformatter -v
esformatter v0.9.3
```

**Comment by millermedeiros** [comment]
this is handled by https://github.com/millermedeiros/esformatter/blob/master/lib/hooks/IfStatement.js - probably caused because of `_br.limitBefore(elseKeyword, 'ElseIfStatement');` (I did not test it tho..)

**Comment by miguelmota** [comment]
is there a fix for this?
