### ISSUE TITLE
Does not format space before "else" in else if statement

### ISSUE THREAD

**Issue by felixhao28** [millermedeiros/esformatter#438]
Is there a way to configure esformatter to format this:

```js
if (a == 1) {
  b;
}else if (a == 2) { // notice the space before else
  c;
} else {
  d;
}
```

into

```js
if (a == 1) {
  b;
} else if (a == 2) { // notice the space before else
  c;
} else {
  d;
}
```

I read your [code](https://github.com/millermedeiros/esformatter/blob/master/lib/hooks/IfStatement.js#L27) and it does not seem to handle that specific space.

**Comment by millermedeiros** [comment]
the code is always formatted the way you expect with the default settings.

the space between `}` and `else` is handled by `whiteSpace.after.IfStatementClosingBrace`, try `esformatter --whiteSpace.after.IfStatementClosingBrace=1` and `esformatter --whiteSpace.after.IfStatementClosingBrace=0` to see the difference in the behavior.
