### ISSUE TITLE
Space in nested objects

### ISSUE THREAD

**Issue by maitriyogin** [millermedeiros/esformatter#442]
Hi,
I want to remove spaces in nested components, mainly for react props.
this
``` {{ marginLeft: 20, marginRight: 20 }} ```
should be 
``` {{marginLeft: 20, marginRight: 20}} ```

I'v tried fiddling with whitespace.before.ObjectExpressionClosingBrace=0 and whitespace.after.ObjectExpressionOpeningBrace=0.
This works great for un-nested components but not for nested components.
any ideas on what properties I need to set?
/Stephen.

**Comment by millermedeiros** [comment]
are you using the [esformatter-jsx plugin](https://github.com/royriojas/esformatter-jsx)?

looks like they don't support this feature yet (they [convert line breaks into a single space](https://github.com/royriojas/esformatter-jsx/blob/2811ca6286fcc62bd7a8e9cd01fc2bd4d5fab091/lib/format-jsx.js#L233-L235), maybe that's the issue), would probably create a feature request there

**Comment by maitriyogin** [comment]
Hi,
Yeah, I'am .. Ok ill post sondering there.
Cheers,
/Stephen 

Sent from my iPhone
