### ISSUE TITLE
if statement format wrong

### ISSUE THREAD

**Issue by futurist** [millermedeiros/esformatter#446]
tested below `if` statement:

```
var a = 1
if(a>1) a=3
else{
  a=2
}
```

after formatted, the result:
```
var a = 1
if (a > 1)
  a = 3else {
  a = 2
}
```

**Comment by millermedeiros** [comment]
need to do something similar to: https://github.com/millermedeiros/esformatter/blob/master/lib/hooks/IfStatement.js#L33-L40 for the `_br.limitBefore(elseKeyword, 'ElseStatement');` inside `else if (alt.type === 'BlockStatement')`

I won't have time to work on it this week, PRs are highly appreciated.

see: https://github.com/millermedeiros/esformatter/commit/a3599b7c092bbd636bfed154d95d7e6b49064e87 and #426
