### ISSUE TITLE
bin global

### ISSUE THREAD

**Issue by lagden** [millermedeiros/esformatter#447]
Hi Miller,

I use the `esformatter` with `Sublime`, but something weird happened...
I did animated gif to show you:

### npm link with original code

![es](https://cloud.githubusercontent.com/assets/130963/16081818/8d5f4b2c-32e5-11e6-94b7-c8d34b78089d.gif)

See the `which` command doesn't show the `esformatter` path

---

### npm link with another name
Now see what happens when I change the name...

![xxxes](https://cloud.githubusercontent.com/assets/130963/16081831/a35ec132-32e5-11e6-8a4b-c23e74fc58c9.gif)

---

Do you have any idea what's going on?

**Comment by millermedeiros** [comment]
no idea what could be happening here... is this breaking anything for you?

**Comment by lagden** [comment]
I did another symlink to adjust this for now.
I think it is a bug in my machine! 😢 
Thanks anyway!
