### ISSUE TITLE
how to disable all formatters

### ISSUE THREAD

**Issue by graingert** [millermedeiros/esformatter#451]
I only want to use one specific formatter, what config will disable all the others?

**Comment by millermedeiros** [comment]
right now there is no way to do it..

we currently always change the indentation and there are some things that we do to the code that are not configurable.

https://github.com/millermedeiros/esformatter/issues/113 explains some of the things that would need to change to make this possible... but it is definitely not a trivial task.

**Comment by millermedeiros** [comment]
maybe for your specific case, setting all options as `-1` would do the trick... but there will always be things that we change no matter what options are set.
