### ISSUE TITLE
merge with lebab

### ISSUE THREAD

**Issue by graingert** [millermedeiros/esformatter#453]
Lebab is another tool that does JS autofixing, but focussed on fixers like let and const

https://github.com/mohebifar/lebab

**Comment by millermedeiros** [comment]
there is no way to implement the features we have on esformatter on top of `lebab`.. they use https://github.com/benjamn/recast internally - which have it's own printer/formatter...

the thing about the "printer" approach is that it receives an AST as input and it decides how to convert that AST into code... so if we "reprint" the whole program, it will be a "destructive" operation (it will remove optional tokens like "()" and all whitespaces/linebreaks)

`recast`/`lebab` could reuse esformatter tho... (the same way as [jsfmt](https://github.com/rdio/jsfmt) does)

**Comment by graingert** [comment]
Looks like everyone needs to use cst
