### ISSUE TITLE
Incorrectly format on a switch case

### ISSUE THREAD

**Issue by felixhao28** [millermedeiros/esformatter#456]
Esformatter formats this (expected)

```js
const a = {
  g() {
    switch (x) {
      case 1:
        ret = 0;
        break;
    }
  },

  f() {}
};
```

into this:

```js
const a = {
  g() {
    switch (x) {
      case 1: ret = 0;
        break;
    }
  },

  f() {}
};
```

I think it is a bug because if `f() {}` is removed then it works as expected.

**Comment by millermedeiros** [comment]
thanks for reporting the bug! we did not have any special code to handle the method syntax!
