### ISSUE TITLE
return in parenthesis inconsistency

### ISSUE THREAD

**Issue by initialize** [millermedeiros/esformatter#465]
```
return (
boop
)
return (
boop
);
```

becomes

```
return (
    boop
)
return (
    boop
    );
```

Not sure if intentional. 

Relevant for JSX, with markup within parenthesis, though formatting seems to be done by esformatter core.

**Comment by millermedeiros** [comment]
this definitely needs to be fixed, should not be hard for this specific case.

this is handled by `getIndentEdges` inside https://github.com/millermedeiros/esformatter/blob/master/lib/hooks/ReturnStatement.js

maybe the parenthesis check is wrong, or maybe it should not return the `parentheses.closing` as the `endToken`.

I'm not going to have time to work on esformatter this week, PRs are highly appreciated! Thanks for reporting the bug.

see also #298 (which is way harder to fix, but somehow related)

**Comment by glesage** [comment]
Indeed, this is still an issue. Any updates?

**Comment by millermedeiros** [comment]
@glesage been busy with my day job, newborn daughter and mountain biking.. only had time to fix this today. will try to release a new version soon including the fix :D

pull requests are highly appreciated!
