### ISSUE TITLE
Sort Plug-ins Wiki Alphabetically

### ISSUE THREAD

**Issue by loganknecht** [millermedeiros/esformatter#471]
Hey there. Love the esformatter. From what I've seen it's pretty slick.

Low-effort, low-priority, not really amazing request.

Can you organize your wiki page for plug-ins alphabetically?

See here:
https://github.com/millermedeiros/esformatter/wiki/Plugins

Thank you regardless!

**Comment by millermedeiros** [comment]
@loganknecht we also have the http://pgilad.github.io/esformatter-plugins/ site that loads npm packages that are marked with the `esformatter-plugin` tag. Feel free to reorder the list. I wont have time to do it.

**Comment by loganknecht** [comment]
Hey there.

Didn't realize I had access to the wiki.

This has been fixed! Thanks for letting me contribute in a small way :)
