### ISSUE TITLE
Template Strings issue

### ISSUE THREAD

**Issue by MikeLP** [millermedeiros/esformatter#474]
for example

`Some Template Strings ${name} ${surname}`

will converted into 

__TEMPORARY_VARIABLE__PLACEHOLDER___NODE__0_

**Comment by millermedeiros** [comment]
probably JSX plugin fault: https://github.com/royriojas/esformatter-jsx/blob/ebbbc7cf2d8c18a539c275e2450bf90f0ee5afe0/src/plugin.js#L80
