### ISSUE TITLE
Keep linebreaks in import

### ISSUE THREAD

**Issue by AlexDunmow** [millermedeiros/esformatter#476]
Esformatter is turning this:

```
import {
	ONE_THING,
	TWO_THING,
	THREE_THING
} from 'lib'
```
into this
`import { ONE_THING, TWO_THING, THREE_THING } from 'lib'`

How do I tell esformatter not to remove line breaks from the import statement? This doesn't work:

```
    "lineBreak": {
      "after": {
        "ImportSpecifier": 1,
        "ImportSpecifierComma": 1
      }
    },
```

**Comment by millermedeiros** [comment]
I think this is handled by `ModuleSpecifierComma`: https://github.com/millermedeiros/esformatter/blob/master/lib/preset/default-linebreak-after.js#L75

see: https://github.com/millermedeiros/esformatter/blob/master/lib/hooks/ImportSpecifier.js#L22

let me know if that doesn't solve your problem.

**Comment by millermedeiros** [comment]
see also: 

 - input: https://github.com/millermedeiros/esformatter/blob/master/test/compare/custom/module-in.js
 - output: https://github.com/millermedeiros/esformatter/blob/master/test/compare/custom/module-out.js
 - config: https://github.com/millermedeiros/esformatter/blob/master/test/compare/custom/module-config.json

you can set values to `-1` to keep existing formatting, so in this case something like `lineBreak.after.ModuleSpecifierComma = -1`

marking as closed; feel free to reopen if issue persists.
