### ISSUE TITLE
Allow objects expressions on one line (if short enough)

### ISSUE THREAD

**Issue by jzaefferer** [millermedeiros/esformatter#73]
From the jQuery Style Guide:

> Object declarations can be made on a single line if they are short (remember the line length limits). When an object delcration is too long to fit on one line, there must be one property per line.

It provides these two examples:

```js
// Good
var map = { ready: 9, when: 4, "you are": 15 };
 
// Good as well
var map = {
    ready: 9,
    when: 4,
    "you are": 15
};
```

Currently its either multi-line everything or single-line everything. It also questionable whether this project should deal with line length.

Elsewhere we keep line breaks as they are and just make sure whitespace and indent are correct. Could we apply that to ObjectExpression as well? Enforcing line lengths can be done with other tools, e.g. jshint has options for that.

**Comment by millermedeiros** [comment]
reopening since we decided to not close `plugins-wishlist` bugs until they are implemented

**Comment by jzaefferer** [comment]
I wrote a plugin for this, but ended up not using it, since there is no clear definition for "short enough", at least no in the jQuery style guide - and my attempts to define that failed. I can publish it as a proper plugin one day anyway, for now here's the code I have, in case anyone else is interested: https://gist.github.com/jzaefferer/23bef744ffea751b2668

**Comment by bobbyrenwick** [comment]
hey @jzaefferer, please could you publish this as a proper plugin? Could we have a setting that defines the number of keys that makes the object short enough, rather than basing the decision on line length?

**Comment by scottgonzalez** [comment]
How would number of keys ever be a suitable measure?

**Comment by jzaefferer** [comment]
@bobbyrenwick since I currently have no use for that plugin myself, I'm not interested in maintaining it as a proper project. You're welcome to take my gist and use that, its MIT licensed.

**Comment by wbinnssmith** [comment]
hey all, using @jzaefferer's gist [I published a module](https://github.com/wbinnssmith/esformatter-collapse-objects) with some extra functionality and conditions for collapsing these literals, and added support for Array literals. I'm still working out the API and looking into other usecases but let me know if it works for you. Feedback hugely appreciated and of course thanks to @jzaefferer and his enthusiasm for the project.

**Comment by jzaefferer** [comment]
Thanks @wbinnssmith! Nice to see this put into a proper plugin. I've updated the wiki to list it (and removed it from the wish list): https://github.com/millermedeiros/esformatter/wiki/Plugins
